### ISSUE TITLE
Problem with /fedml_experiments/distributed/fedavg/run_fedavg_distributed_pytorch.sh

### ISSUE THREAD

**Issue by yukizhao1998** [FedML-AI/FedML#101]
I think there is some problem with the line: PROCESS_NUM=`expr $WORKER_NUM + 1`
Maybe it should be PROCESS_NUM=`expr $CLIENT_NUM + 1` since WORKER_NUM stands for clients per round and CLIENT_NUM stands for clients in total.

**Comment by chaoyanghe** [comment]
I cannot get your point but you can refer to my answer here:
https://github.com/FedML-AI/FedML/issues/95
