### ISSUE TITLE
Missing partited CIFAR file

### ISSUE THREAD

**Issue by wnma3mz** [FedML-AI/FedML#102]
I could't find `distribution.txt` and `net_dataidx_map.txt`. Are these two files necessary? Or did I misunderstand the code?

https://github.com/FedML-AI/FedML/blob/f26fbe4789dd68ca737b2a06c35e89964baf3b6d/fedml_api/data_preprocessing/cifar10/data_loader.py#L31

https://github.com/FedML-AI/FedML/blob/f26fbe4789dd68ca737b2a06c35e89964baf3b6d/fedml_api/data_preprocessing/cifar10/data_loader.py#L16

Thanks for taking the time to help me!

**Comment by chaoyanghe** [comment]
[distribution.txt](https://github.com/FedML-AI/FedML/files/6008264/distribution.txt)
[Uploading net_dataidx_map.txt…]()

**Comment by chaoyanghe** [comment]
these two are examples

**Comment by wnma3mz** [comment]
Thank you for your prompt reply.
