### ISSUE TITLE
Weight decay and momentum is not set for SGD optimizer

### ISSUE THREAD

**Issue by densechen** [FedML-AI/FedML#106]
https://github.com/FedML-AI/FedML/blob/e0c58c539bf1d7ae9911e57d7f223ac19af03902/fedml_api/standalone/fedavg/my_model_trainer.py#L26

**Comment by wizard1203** [comment]
@densechen Hi, in original paper of FedAvg, Momentum SGD has not been considered. Actually, momentum SGD in current version of FedML has some different behaviors. This will be updated in future work.
