### ISSUE TITLE
Use the nvidia-supplied nvidia-ml-py instead of pynvml

### ISSUE THREAD

**Issue by mattip** [FedML-AI/FedML#1064]
This project [depends on pynvml](https://github.com/search?q=repo%3AFedML-AI%2FFedML%20pynvml&type=code), where the nvidia-blessed bindings to nvml are in the [nvidia-ml-py](https://pypi.org/project/nvidia-ml-py/) package instead. This is causing problems for the [gpustat project](https://github.com/wookayin/gpustat/issues/153#issuecomment-1551036105), which needs some internals from nvidia-ml-py to properly support older nvml version. Would it be possible to switch?

**Comment by fedml-zijianhu** [comment]
This has been solved in #1331
