### ISSUE TITLE
Can you provide an example of grpc？

### ISSUE THREAD

**Issue by canhongpoxiao** [FedML-AI/FedML#107]
I don't quite understand ipconfig about grpc. I think some people may have the same doubts. Thanks.

**Comment by chaoyanghe** [comment]
@canhongpoxiao try this one: https://github.com/FedML-AI/FedML/tree/master/python/examples/cross_silo/grpc_fedavg_mnist_lr_example

**Comment by fedml-dimitris** [comment]
Closing this. Already addressed.
