### ISSUE TITLE
Any sample document for running chatbot example in fedllm

### ISSUE THREAD

**Issue by KumarAshitabh** [FedML-AI/FedML#1078]
Could you please provide command line arguments for running the chatbot example in fedllm 
I am getting "Setting `pad_token_id` to `eos_token_id`:0 for open-end generation" warning continuoulsy when running without assigning any parameters

**Comment by fedml-zijianhu** [comment]
Hi,

We will update the code and the document soon.

Regarding the "Setting `pad_token_id` to `eos_token_id`:0 for open-end generation" warning, you can do the following to turn it off. See [this StackOverflow answer](https://stackoverflow.com/a/71397707) for detail
> `model.generate(**encoded_input, pad_token_id=tokenizer.eos_token_id)`
