### ISSUE TITLE
fail to import FedAvgTrainer for standalone simulation

### ISSUE THREAD

**Issue by NeutrinoLiu** [FedML-AI/FedML#112]
fail at: `from fedml_api.standalone.fedavg.fedavg_trainer import FedAvgTrainer` in both trainer.py and group.py
there is no such fedavg_trainer.py under api/standalone/fedavg/
Then i tried to use the fedavgtrainer under the distributed api, it seems that the factory method from FedAvgTrainer of distributed-api did not match:

> Traceback (most recent call last):
>   File "./main.py", line 52, in <module>
>     trainer = Trainer(dataset, model, device, args)
> TypeError: __init__() missing 4 required positional arguments: 'train_data_num', 'device', 'args', and 'model_trainer'

**Comment by chaoyanghe** [comment]
May I have your script to reproduce this error?

**Comment by NeutrinoLiu** [comment]
```
cd ./fedml_experiments/standalone/hierarchical_fl
sh run_standalone_pytorch.sh 0 1000 1000 -1 mnist ./../../../data/mnist lr hetero 0.03 sgd random 2 5 2 1
```
just use your [CI-script-fedavg.sh](https://github.com/FedML-AI/FedML/blob/3d1323d53d042d21d287b4a158247c14119e7d18/CI-script-fedavg.sh#L50) to 
```
assert that, for full batch and epochs=1 and when the product of global and group comm. round is fixed,
the accuracy of hierarchical federated learning is equal to that of centralized training, regardless of the number of groups
```
import failed at [group.py](https://github.com/FedML-AI/FedML/blob/e0c58c539bf1d7ae9911e57d7f223ac19af03902/fedml_api/standalone/hierarchical_fl/group.py#L4) and same line for trainer.py.

The error msg i mentioned above occurs when i try to import the FedAvgTrainer from distributed configuration dir where they do have a definition of FedAvgTrainer class.

**Comment by ljn1999** [comment]
Hello, I have exact the same issue here, there's no fedavg_trainer module under fedml_api.standalone.fedavg.
Do you have an idea of how to fix it? Thanks!
