### ISSUE TITLE
How to use grpc to communicate between server and client

### ISSUE THREAD

**Issue by Lizhihzzx** [FedML-AI/FedML#114]
i want to try grpc mode to run the app.py demo, and there comes the problem like this:
AttributeError: 'Namespace' object has no attribute 'grpc_ipconfig_path'
how to config grpc_ipconfig_path to use grpc to communicate

**Comment by mzp0625** [comment]
Hi, 

Please pull the latest [FedML-Server submodule](https://github.com/FedML-AI/FedML-Server/tree/master). It has been updated to include this argument. You will also find a file at executor/grpc_ipconfig.csv - make edits to it [like this](https://github.com/FedML-AI/FedML/tree/master/fedml_experiments/distributed/fedavg#setting-ip-configurations-for-grpc).
Note for running on different devices, you will need to have a copy of config file at both the server and clients. 

Let me know if you have further questions.
