### ISSUE TITLE
Weird accuracy while running fedml-iot with default cnn on MNIST

### ISSUE THREAD

**Issue by MichaelLee-ceo** [FedML-AI/FedML#117]
It's normal while training under the linear regression on MNIST, but when I change the model to CNN which is located in /fedml_api/model/cv/cnn.py it trains weirdly, are there any solutions for that? Thanks!

**Comment by chaoyanghe** [comment]
what's the issue you met?

**Comment by MichaelLee-ceo** [comment]
How are the steps to execute the cnn version correctly?

**Comment by chaoyanghe** [comment]
@MichaelLee-ceo you need to tune the hyper-parameters to make it work. Here are some references:
https://github.com/FedML-AI/FedML/tree/master/benchmark

Could you share the path and the script you run the experiment?
