### ISSUE TITLE
Does fedml implement encryption currently?

### ISSUE THREAD

**Issue by dejavu6** [FedML-AI/FedML#118]
Hello, I would like to ask , does  fedml implement encryption currently?

**Comment by JcYBalaBalA** [comment]
I have same question，but until today I do not find any worthy answer

**Comment by chaoyanghe** [comment]
we do have MPC-based algorithm, check this example: https://github.com/FedML-AI/FedML/tree/master/python/examples/cross_silo/light_sec_agg_example. It's our new paper published at MLSys 2022: https://proceedings.mlsys.org/paper/2022/hash/d2ddea18f00665ce8623e36bd4e3c7c5-Abstract.html

Also, we provide many security (attack/defense), DP related APIs:
https://github.com/FedML-AI/FedML/tree/master/python/fedml/core

**Comment by fedml-dimitris** [comment]
Closing this due to duplication. Please see here:
https://github.com/FedML-AI/FedML/issues/108
