### ISSUE TITLE
Implementation issue about standalone Fedavg

### ISSUE THREAD

**Issue by DryDew** [FedML-AI/FedML#119]
Hi, 
I'm new to FedML. I just get confused with the testing part of standalone Fedavg. In the file "fedml_api/standalone/fedavg/fedavg_api.py", the implementation of function "_local_test_on_all_clients" seems not correct. 

It seems that the current implementation uses a fixed instance of Client to test all clients. However, the model is not switched in the for loop. 

Please correct me if I have a wrong understanding.

Thanks!

**Comment by chaoyanghe** [comment]
it's a global model instance, so it's ok. If we would like to do personalization, then we should use the personalized models
