### ISSUE TITLE
shell script has some issue at line 13 during installation

### ISSUE THREAD

**Issue by MakGulati** [FedML-AI/FedML#122]
https://github.com/FedML-AI/FedML/blob/400072ef5daa9a9ca0f205ff3a90ccf13f975729/CI-install.sh#L11

**Comment by thuydang** [comment]
This happens to me when running the script with sh:
`sh CI-install.sh`

**Cause:**
sh invokes source as external program, which it is not.

**Solutions:**
1. Make the script executable and run it with dot (.):
    chmod +x CI-install.sh
    ./CI-install.sh
2. Change the line in the code, replace source with (.):
     . "$HOME/miniconda/etc/profile.d/conda.sh"

**Suggestion:**
Provide more details how to execute the scripts in the [documentation](http://doc.fedml.ai/#/installation-standalone-simulation)
