### ISSUE TITLE
standalone: main_fedavg.py: error: argument --comm_round: invalid int value: 'hetero'

### ISSUE THREAD

**Issue by liyang-good** [FedML-AI/FedML#124]
I want to test run_fedavg_standalone_pytorch.sh, however, print :  invalid int value: 'hetero'

hetero 代表什么，我可以去哪个文件夹查看这个参数的含义? thanks 

![image](https://user-images.githubusercontent.com/71406269/119598820-3dc7e300-be16-11eb-959c-7ee8158caee9.png

**Comment by wangzhenzhou2020** [comment]
我没遇到这个问题耶。命令和你一样。

**Comment by liyang-good** [comment]
你好，
1，上次有位朋友，看他的文件，我修改了参数，可以跑。

2. 运行这个命令，我现在会遇到这种问题，wandb这个不知怎么设置了，需要连接外网吗？谢谢。


发件人: wangzhenzhou2020
发送时间: 2021年6月7日 10:17
收件人: FedML-AI/FedML
抄送: liyang-good; Author
主题: Re: [FedML-AI/FedML] standalone: main_fedavg.py: error: argument--comm_round: invalid int value: 'hetero' (#124)

我没遇到这个问题耶。命令和你一样。

**Comment by liyang-good** [comment]
![image](https://user-images.githubusercontent.com/71406269/120985683-6e146780-c7ae-11eb-9289-2272a0e26c56.png)

**Comment by wangzhenzhou2020** [comment]
这个问题我也没碰到。我的服务器是这样的：在CI-install里的九个数据集，有2、3个需要从google下载，我的服务器不能下载这2、3个。但服务器可以使用wandb。
我是这样使用 wandb 的：
1 安装 wandb
2 wandb login （运行它会生成链接，取得api_keys，然后复制粘贴，回车，就登陆了。前提是你有wandb的账户）
3 wandb init（...） 
4 wandb log（...）
第3、4 步 看官网教程，或者百度、知乎学习吧。

**Comment by liyang-good** [comment]
好的，感谢！
