### ISSUE TITLE
fedml_experiments/distributed/fedavg  run_fedavg_distributed_pytorch.sh  stuck

### ISSUE THREAD

**Issue by wangzhenzhou2020** [FedML-AI/FedML#126]
find the  problem, for every worker(process):
![image](https://user-images.githubusercontent.com/67401289/120954417-b9fce780-c781-11eb-97ad-98031a8c0793.png)

eventually, it stucks at:
![image](https://user-images.githubusercontent.com/67401289/120954536-fc262900-c781-11eb-893e-05f4d1cc6890.png)

**Comment by wangzhenzhou2020** [comment]
anybody encountered this problems？

**Comment by wangzhenzhou2020** [comment]
thanks. i've solved that problem (just as you said) two weeks ago. But , i've encounted another problem: 
at the final round,  FedAvgServerManager.py call  FedAVGAggregator.py(the red arrow)  . 
![image](https://user-images.githubusercontent.com/67401289/124059857-61f29180-da5e-11eb-80d8-473cc27dd498.png)

But in the FedAvgAggregator.py ,  test_on_server_for_all_clients(),  sometimes , the last line , logging.info(stats) , can't log the test_acc and test_loss.
![image](https://user-images.githubusercontent.com/67401289/124060110-e9d89b80-da5e-11eb-96b5-c77b9fbf8756.png)

At the last line ,  it logs the test_acc and test_loss.
the here 1 ... here 6 are used for helping me debug.

Now , first, i show the normal ways the code ends: 

![image](https://user-images.githubusercontent.com/67401289/124058950-e6dcab80-da5c-11eb-9c67-f8348ca738c6.png)
You can see the  test_acc and test_loss (In FedAvgAggregator.py ). and   __finish (In FedAvgServerManager.py )

But, sometimes the code ends  weird:
![image](https://user-images.githubusercontent.com/67401289/124059554-db3db480-da5d-11eb-967d-a442b3cad266.png)

Or:
![image](https://user-images.githubusercontent.com/67401289/124060463-b1858d00-da5f-11eb-87ea-5bd9e9c9cf5d.png)

It may ends at here 1 ...... here 6 .  

Do you have the same problem？

**Comment by 897123856413** [comment]
怎么解决，对应不上，这个文件在什么下面啊

**Comment by 897123856413** [comment]
代码行数不对应啊

，还是卡着呢

**Comment by 897123856413** [comment]
> Please comment or delete line 62-64 in FedAvgClientManager.py and line 59-63 in FedAvgServerManager.py. This will fix your problem还是不行，卡在中间呢

**Comment by jackdoll** [comment]
I want to ask you how you run  run_fedavg_distributed_pytorch.sh successfully? I tried to run it on a single computer with a single GPU, but it always told me the error "mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated."

**Comment by rG223** [comment]
@wangzhenzhou2020 I have a question about distribution, why gpu usage is very strange, CUDA0 is the fastest and CUDA3 is the slowest, there is a 10-fold difference in speed, and slow Gpus will run out of memory later.

**Comment by chaoyanghe** [comment]
@rG223 @jackdoll @897123856413 

please check our new examples at: https://github.com/FedML-AI/FedML/tree/master/python/examples

We've upgraded our library a lot in recent version. Here is a brief introduction:
https://medium.com/@FedML/fedml-ai-platform-releases-the-worlds-federated-learning-open-platform-on-public-cloud-with-an-8024e68a70b6
