### ISSUE TITLE
possible error in MNIST data loader

### ISSUE THREAD

**Issue by mansiparashar** [FedML-AI/FedML#131]
Hello, I am getting a weird path not found error.
Am I doing something wrong?
![image](https://user-images.githubusercontent.com/41821164/124180311-a1a69100-dad1-11eb-9af5-a61edca363a5.png)

**Comment by mansiparashar** [comment]
update: I changed it to absolute path and it worked. 🤷‍♀️

**Comment by KOUDA-AMINE** [comment]
this worked for me :

train_path = "../../../data/MNIST/train"
test_path = "../../../data/MNIST/test" 

instead of :

 train_path = "../../FedML/data/MNIST/train"
 test_path = "../../FedML/data/MNIST/test"
