### ISSUE TITLE
Missing Lending Club Dataset

### ISSUE THREAD

**Issue by RyanMarten** [FedML-AI/FedML#132]
The link mentioned at https://github.com/FedML-AI/FedML/tree/master/data/lending_club_loan to download the lending club dataset is now dead. The user may have removed the dataset from Kaggle. Can you please upload the dataset to Google Drive and provide an alternative download link?

**Comment by chaoyanghe** [comment]
Yes, it's served at AWS https://github.com/FedML-AI/FedML/commit/4b8667d8e1c129a01b3017fc1ff7be8a80df0f56
