### ISSUE TITLE
The subscript of the client does not correspond~

### ISSUE THREAD

**Issue by Dawnxxx** [FedML-AI/FedML#134]
Please give me a suggestion on how to modify it!
![image](https://user-images.githubusercontent.com/42707915/126022043-bf877a06-c08c-4225-b8ec-59d03ba851c8.png)
![Uploading image.png…]()

**Comment by Dawnxxx** [comment]
![image](https://user-images.githubusercontent.com/42707915/126022144-3bd1afd8-318a-4495-bd6a-b97ea279c570.png)

**Comment by AbdulmoneamAli** [comment]
![image](https://user-images.githubusercontent.com/88114482/128404692-cc772eb0-1b9b-44a2-a502-e4bb695c55ee.png)
