### ISSUE TITLE
download link of dataset lending_club_loan is not valid 

### ISSUE THREAD

**Issue by CHR-ray** [FedML-AI/FedML#137]
https://github.com/FedML-AI/FedML/tree/master/data/lending_club_loan need to download dataset from the link https://www.kaggle.com/wendykan/lending-club-loan-data, but this link is not valid anymore. Can someone has downloaded the files to share it again? 

Thank you !

**Comment by chaoyanghe** [comment]
@CHR-ray Yes. it's updated to AWS: https://github.com/FedML-AI/FedML/commit/4b8667d8e1c129a01b3017fc1ff7be8a80df0f56
