### ISSUE TITLE
what is the purpose for parameter 'CI'

### ISSUE THREAD

**Issue by sean-xia** [FedML-AI/FedML#140]
Please find the ‘CI' at the bottom of this text
python3 ./main_fedavg.py \
--gpu $GPU \
--dataset $DATASET \
--data_dir $DATA_PATH \
--model $MODEL \
--partition_method $DISTRIBUTION  \
--client_num_in_total $CLIENT_NUM \
--client_num_per_round $WORKER_NUM \
--comm_round $ROUND \
--epochs $EPOCH \
--batch_size $BATCH_SIZE \
--client_optimizer $OPT \
--lr $LR \
--ci $CI    #how dose this parameter influnce the trainning results?

**Comment by yangyong-y** [comment]
"""
            Note: CI environment is CPU-based computing. 
            The training speed for RNN training is to slow in this setting, so we only test a client to make sure there is no programming error.
            """
            if self.args.ci == 1:
                break
