### ISSUE TITLE
No module named 'FedML'

### ISSUE THREAD

**Issue by shanullah** [FedML-AI/FedML#145]
I am new to FedML and highly interested in fedGKT, 

I followed this  "an easy way to install is to follow the script at CI-install.sh (https://github.com/FedML-AI/FedML/blob/master/CI-install.sh) and CI-script-fedavg.sh (https://github.com/FedML-AI/FedML/blob/master/CI-script-fedavg.sh)"

I have run the above commands, but after successful installations, I could not run the https://github.com/FedML- AI/FedML/tree/master/fedml_experiments/distributed/fedgkt

sh run_FedGKT.sh 0 cifar10 homo 200 1 20 Adam 0.001 1 0 resnet56 fedml_resnet56_homo_cifar10 "./../../../data/cifar10" 256

Later, I tried to run a simple fedavg example in a distributed folder, but the same error.

I have tried on my two different PCs (Ubuntu installed) but came up with the same errors as shown in the images below.

please guide me in case I have missed anything. Thank you so much.

![error_at_Fedavg](https://user-images.githubusercontent.com/25828634/136339577-4fc01b4e-e4bc-4f67-93ba-8ec7d9d7de37.jpeg)
![error_at_fedGKT](https://user-images.githubusercontent.com/25828634/136339589-f1b8760d-0110-4ef5-bd7c-cddce299ac42.jpeg)

**Comment by flashlau** [comment]
I get the same issue when I run the code. The root folder's name should be renamed as "FedML".

**Comment by baobaochai** [comment]
> 



> Based on valuable comments by @ChaoYANG He, I am glad that I could resolve a very basic issue related particularly to my environment. By modifying the lines by removing FedML from FedML.fedml_core to fedml_core..., I could run it successfully. thank you so much for such a prompt response on slack and your guidance. Now I can proceed further



i am studying this codes recently, but i had met above issues. i am confused with what you said, would you mind share your complete codes with me?

**Comment by baobaochai** [comment]
> > 
> 
> > Based on valuable comments by @ChaoYANG He, I am glad that I could resolve a very basic issue related particularly to my environment. By modifying the lines by removing FedML from FedML.fedml_core to fedml_core..., I could run it successfully. thank you so much for such a prompt response on slack and your guidance. Now I can proceed further
> 
> i am studying this codes recently, but i had met above issues. i am confused with what you said, would you mind share your complete codes with me?

you can get contact with me through my email: bbchai_915@sdust.edu.cn, I would be very grateful if  you could give me a hand.
