### ISSUE TITLE
Is it possible to run FedML properly on tx2?

### ISSUE THREAD

**Issue by YourPeer** [FedML-AI/FedML#148]
I would like to try using my host as the server and a few tx2s as end-side training devices, would this work?

**Comment by chaoyanghe** [comment]
@YourPeer do you mean this device?http://www.radiometrix.com/content/tx2s

**Comment by chaoyanghe** [comment]
@YourPeer our latest FedIoT repo is at: https://github.com/FedML-AI/FedML/tree/master/iot

**Comment by fedml-dimitris** [comment]
Closing this issue since it is already addressed.
