### ISSUE TITLE
something wrong in FedML/fedml_api/standalone/hierarchical_fl group.py and trainer.py

### ISSUE THREAD

**Issue by cccrick** [FedML-AI/FedML#152]
In `FedML/fedml_api/standalone/hierarchical_fl/group.py` line 4，
`from fedml_api.standalone.fedavg.fedavg_trainer import FedAvgTrainer` 
don't exist.
I have tried to modify to my_model_trainer.py in fedml_api.standalone.fedavg, the params is error. And modified to  FedAVGTrainer.py in fedml_api/distributed/fedavg, same error.

The command in the CI-script-fedavg.sh of hierarchical-fl is wrong. The command is follow
```Shelll
cd ./fedml_experiments/standalone/hierarchical_fl
sh run_standalone_pytorch.sh 0 1000 1000 -1 mnist ./../../../data/mnist lr hetero 0.03 sgd random 2 5 2 1
```
The same problem exist in the trainerl.py.

**Comment by chaoyanghe** [comment]
Check our latest examples at:
https://github.com/FedML-AI/FedML/tree/master/python/examples

We've upgraded our library a lot in recent version. Here is a brief introduction:
https://medium.com/@FedML/fedml-ai-platform-releases-the-worlds-federated-learning-open-platform-on-public-cloud-with-an-8024e68a70b6
