### ISSUE TITLE
code wrong？？

### ISSUE THREAD

**Issue by NexusAkio** [FedML-AI/FedML#153]
![image](https://user-images.githubusercontent.com/51773504/139662157-a3bd0eec-7dfd-4607-aad5-92b2d9bb9adf.png)

Obviously, client_sampling in line 33 returns a list with length client_num_per_round. Why is the loop size-1 in lines 38 and 39? In this way, the client_indexes[process_id-1] in line 39 will exceed the index range.

**Comment by NexusAkio** [comment]
The code is in the py file named FedAVGServerManager

**Comment by chaoyanghe** [comment]
think about the following example, you will see why.

```
 client_indexes = [2, 3, 7, 9]

server process id = 0
worker process id = 1, 2, 3, 4

size = 5

```
