### ISSUE TITLE
why does fednlp disappear?

### ISSUE THREAD

**Issue by springfall2018** [FedML-AI/FedML#1540]
https://github.com/FedML-AI/FedML/tree/master/python/app/fednlp does not have any content but shows "Page 404"
When can you restore it?

**Comment by fedml-dimitris** [comment]
@springfall2018, it has not disappeared, it has been moved under prebuilt_jobs:
https://github.com/FedML-AI/FedML/tree/master/python/examples/federate/prebuilt_jobs/fednlp
