### ISSUE TITLE
error in GPU_MAPPING.md

### ISSUE THREAD

**Issue by flashlau** [FedML-AI/FedML#155]
Error in file https://github.com/FedML-AI/FedML/blob/master/fedml_experiments/distributed/fedavg/GPU_MAPPING.md.
In section "Skip some GPU devices inside a machine", configuration for client2 and client3 is wrong. It should be "client 2 -- host2:GPU:0, client 3 -- host2:GPU:2".

**Comment by chaoyanghe** [comment]
Thank you for your feedback. We will fix the wording.
