### ISSUE TITLE
 distributed的.sh传参找不到学习率,要不就是找不到batch_size.argument --comm_round: invalid int value: 'lr'

### ISSUE THREAD

**Issue by 897123856413** [FedML-AI/FedML#158]
传参时候 standalone可以，distributed的.sh传参找不到学习率要不就是找不到batch_size
argument --comm_round: invalid int value: 'lr'

**Comment by chaoyanghe** [comment]
@897123856413 which script and what's the related error logs? We are trying to reproduce it.
