### ISSUE TITLE
Where can I find FedGraphNN?

### ISSUE THREAD

**Issue by SpeeeedLee** [FedML-AI/FedML#1632]
I follow the paper about FedGraphNN(https://iclr.cc/virtual/2021/4186) to here, but I can find it, will anyone please guide me to it ? 

Thanks a lot.

**Comment by fedml-dimitris** [comment]
@SpeeeedLee please have a look here:
https://github.com/FedML-AI/FedML/tree/master/python/examples/federate/prebuilt_jobs/fedgraphnn

**Comment by SpeeeedLee** [comment]
Thank you for your help !
