### ISSUE TITLE
Customized total number of users in a stand-alone environment

### ISSUE THREAD

**Issue by yangyong-y** [FedML-AI/FedML#165]
The default is 1000 users, how can I divide all data among 100 or 50 users? It seems that only some users can be selected from the 1,000 users as the total number of customers, not all the data is used

**Comment by chaoyanghe** [comment]
@yangyong-y you can customize the data loader. Examples are here:
https://github.com/FedML-AI/FedML/tree/master/fedml_api/data_preprocessing/cifar10
