### ISSUE TITLE
fedml_experiments/distributed/fedavg run_fedavg_distributed_pytorch.sh stuck in one computer with one GPU

### ISSUE THREAD

**Issue by jackdoll** [FedML-AI/FedML#166]
I just have one computer with one GPU, I want to run three processes on one GPU to simulte one server and two clients, so I set the gpu_mapping.yaml as mapping_default: ChaoyangHe-GPU-RTX1080Ti: [3], and run "sh run_fedavg_distributed_pytorch.sh 2 2 resnet56 homo 1 1 64 0.001 cifar10 "./../../../data/cifar10" sgd 1".  But it always has the error "mpirun detected that one or more processes exited with non-zero status, thus causing the job to be terminated."  How to solve the problem? Or can you tell me how to run distributed FL if I only have one computer with one GPU？

**Comment by KOUDA-AMINE** [comment]
Did you change the 'ChaoyangHe-GPU-RTX1080Ti' to your hostname?

**Comment by chaoyanghe** [comment]
@jackdoll is this issue solved in the latest examples?
https://github.com/FedML-AI/FedML/tree/master/python/examples
