### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'recv'

### ISSUE THREAD

**Issue by Alhonainy21** [FedML-AI/FedML#168]
Hello,
I followed the same instructions for FedML IotT for raspberry pi 4, however, when I run app.python in fedml_server_executer, I got this issue:

```
AttributeError: 'NoneType' object has no attribute 'recv'
Traceback (most recent call last):
  File "/home/pi/FedML-IoT/FedML/fedml_core/distributed/communication/mpi/mpi_receive_thread.py", line 23, in run
    msg_str = self.comm.recv()
```

Anyone can help please?

**Comment by chaoyanghe** [comment]
@Alhonainy21 Thanks for your feedback. I will ask @zhang-tuo-pdf to help you.

**Comment by zhang-tuo-pdf** [comment]
The reason why you meet this problem is that you did not initiate the client with the server. Please check the readme in the fediot repo. 
https://github.com/FedML-AI/FedIoT/tree/main/experiments/Resberry_Pi
