### ISSUE TITLE
How to assign multi-cores to one client (or one process of MPI) when trainning only use CPU?

### ISSUE THREAD

**Issue by zuoxiaojiang** [FedML-AI/FedML#173]
FedML starts with command of ‘mpirun’, and only assigns one cpu core to each process. As far as I know, 'mpi4py' used by FedML can not support multi-cores per process, and thus limits the performance of model training on each client. 

Hence, is there any suggestion to solve this problem?

**Comment by chaoyanghe** [comment]
@zuoxiaojiang Hi, the number of CPU cores used by the process launched by MPI is OS-dependent. See the discussion here: https://stackoverflow.com/questions/5797615/mpi-cores-or-processors

**Comment by chaoyanghe** [comment]
Say you have N CPUs and each CPU has M cores, you will have N*M cores. If you create K processed using MPI, the number of cores per process will be (N*M)/K.

**Comment by zuoxiaojiang** [comment]
OK～ Thank you.



发自我的iPhone


------------------ Original ------------------
From: Chaoyang He ***@***.***&gt;
Date: Sat,Apr 16,2022 3:19 AM
To: FedML-AI/FedML ***@***.***&gt;
Cc: zuoxiaojiang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [FedML-AI/FedML] How to assign multi-cores to one client (or oneprocess of MPI) when trainning only use CPU? (Issue #173)





 
Say you have N CPUs and each CPU has M cores, you will have NM cores. If you create K processed using MPI, the number of cores per process will be (NM)/K.
