### ISSUE TITLE
Miss many arguments in most of the experiments.

### ISSUE THREAD

**Issue by JLU-Neal** [FedML-AI/FedML#178]
Very bad experience in running experiments.

**Comment by chaoyanghe** [comment]
@JLU-Neal Thanks for your feedback. Which experiment and related arguments do you refer to? 

We have an internal version, upgraded for 1-2 years, will be released soon. The arguments have been upgraded as yaml file style. Please look forwards to our new version.

**Comment by JLU-Neal** [comment]
Great! Seems better!
