### ISSUE TITLE
Unable to run FedML Mobile

### ISSUE THREAD

**Issue by garganubhav** [FedML-AI/FedML#18]
Hi, I want to do on-device federated learning on an android phone. I followed the limited instructions but was not able to run a server and client process. I want to run my custom model. Is this tool not ready for mobile yet? Thanks

**Comment by chaoyanghe** [comment]
Thank you for following this work.
FedML-Mobile is still under development. We will release the first version around mid of September.

**Comment by chaoyanghe** [comment]
FedML Mobile Server is ready! Please check our latest code.

**Comment by garganubhav** [comment]
Thank you for the quick response. Can you give an example or instructions on how can it be used if we want to train a custom model on mobile? I am a newbie in this and would appreciate it.
