### ISSUE TITLE
Pretrained models on imagenet for cifar10 and cifar100 provided in the repo are different

### ISSUE THREAD

**Issue by AArchLichKing** [FedML-AI/FedML#190]
Hi, 

Thanks for your excellent work on this excellent repo. 

I came across the following questions, pretrained models on imagenet for cifar10 and cifar100 provided in the repo are different. Specifically, the following codes lead to the following output. This seems weird to me, since if they are all pretrained on ImageNet then, they should be the same? 

Thanks very much for your help!!

```
state_dict1 = torch.load("./../../../fedml_api/model/cv/pretrained/CIFAR10/resnet56/best.pth")['state_dict']
state_dict2 = torch.load("./../../../fedml_api/model/cv/pretrained/CIFAR100/resnet56/best.pth")['state_dict']

for (k1, v1), (k2, v2) in zip(state_dict1.items(), state_dict2.items()):
    print(k1==k2, k1)
    print((v1 == v2).all())
```

![image](https://user-images.githubusercontent.com/50974944/165471075-31aa7253-6827-4e39-8f09-02f3fb57670f.png)

**Comment by chaoyanghe** [comment]
@AArchLichKing Hi we've released a new version of FedML framework. Could you help to reproduce this issue again? I am not sure whether it still exist.

**Comment by AArchLichKing** [comment]
@chaoyanghe Sure, I am happy to, and that's so great that you excellent guys are keeping improving codes. But I cannot find those models, lol, can you help me locate them? :)

**Comment by chaoyanghe** [comment]
Do you mean this? https://github.com/FedML-AI/FedML/tree/master/python/fedml/model

Probably our engineers have removed the pretrained model to accelerate the speed of github clone. Which files do you need?

For the new repo, please read through https://doc.fedml.ai

**Comment by AArchLichKing** [comment]
I think so. So what I need is the pretrained resnet56 on ImageNet, which was originally located at './../../../fedml_api/model/cv/pretrained/CIFAR10/resnet56/best.pth'. I have searched for a while but cannot find a pretrained resnet56 on Imagenet

**Comment by chaoyanghe** [comment]
@AArchLichKing I see. I guess we removed them because they are too big for the source. I think you can find such pretrained models easily at pytorch ecosystem.
