### ISSUE TITLE
I can't run the hierarchical_fl experiment 

### ISSUE THREAD

**Issue by Bhongcheng** [FedML-AI/FedML#191]
Hello, I am a Chinese student. When I try to run the hierarchical_fl.main.py, I get an error:

Traceback (most recent call last):
  File "C:/Users/BHC/PycharmProjects/FedML_practice/fedml_experiments/standalone/hierarchical_fl/main.py", line 52, in <module>
    trainer = Trainer(dataset, model, device, args)
TypeError: __init__() takes from 2 to 3 positional arguments but 5 were given

    I am very poor in programming and I don't change any code. I may know the reason why this could happen but I don't know how to solve it. Could anyone please help me and give me a little suggestions? Thank you from the bottom of my heart!

**Comment by Bhongcheng** [comment]
It seems that nobody would like to help me :(

**Comment by Bhongcheng** [comment]
By checking out the previous version, I successfully run the hierarchical_fl experiment!

**Comment by chaoyanghe** [comment]
@Bhongcheng Hi sorry for the late reply. We were busy at refactoring the source code. Could you please help to double check whether the latest version works? If not, please help pull request your modification/fix.
