### ISSUE TITLE
The arXiv uid  in citation is from Horovod

### ISSUE THREAD

**Issue by Lyken17** [FedML-AI/FedML#2]
Hi Chaoyang,

In current branch, the arXiv uid ([1802.05799](https://arxiv.org/abs/1802.05799)) is about horovod. You may want to update it with your own one.  

```
@article{chaoyanghe2020fedml,
  Author = {Chaoyang He},
  Journal = {arXiv preprint arXiv:1802.05799},
  Title = {FedML: a Flexible and Generic Federated Learning Library and Benchmark},
  Year = {2020}
}
```

**Comment by FedML-AI** [comment]
Hi Ligeng, thanks for your feedback. We've submitted our paper draft to Arxiv and the actual link will be available in several days. I just put the paper draft for our own website: https://www.fedml.ai/publication/fedml.pdf

**Comment by chaoyanghe** [comment]
@Lyken17 Hi Ligeng, we've improved a lot recently. Please have a try again.
