### ISSUE TITLE
代码跑不起来（fedavg算法）

### ISSUE THREAD

**Issue by fengyann** [FedML-AI/FedML#20]
在中心服务器端可以免密登录客户端，其他软件也配置好了，但是为什么在服务器端运行代码的时候识别不了客户端的主机名呢

**Comment by FedML-AI-admin** [comment]
Please provide the following information to help us to locate your issue:
1. OS
2. package versions (MPI4py, Python, etc)
3. hardware topology

We have a one-key script "CI-script-fedavg.sh". You can also follow it to set up your environment.

**Comment by fengyann** [comment]
已解决谢谢！
