### ISSUE TITLE
About the hierarchical FL

### ISSUE THREAD

**Issue by Bhongcheng** [FedML-AI/FedML#211]
Sorry to disturb you, I want to know whether the Hierarchical FL will come in the future.  I click the link [https://github.com/FedML-AI/FedML/blob/master/doc/en/cross-silo/examples/hierarchical_fedavg_mnist_lr_example.md](url) but find 404.

**Comment by chaoyanghe** [comment]
@Bhongcheng Hi, the correct link is at:

https://github.com/FedML-AI/FedML/tree/master/python/examples/cross_silo/mqtt_s3_fedavg_hierarchical_mnist_lr_example

**Comment by Bhongcheng** [comment]
Thank you very much!
