### ISSUE TITLE
[windows] Unable to import FedML

### ISSUE THREAD

**Issue by Mojahed-nour** [FedML-AI/FedML#213]
I have installed the official FedML package with Anaconda. but when I imported the package(see the Fig), it showed that 'from mpi4py import MPI
ImportError: DLL load failed: The specified procedure could not be found'. 
![image](https://user-images.githubusercontent.com/67114907/167048359-04ef8e9e-eb8d-47fe-8908-cb7affaf90b9.png)

Is this way incorrect? Thanks)

**Comment by chaoyanghe** [comment]
how about adding one more command:

```
conda install mpi4py
```

**Comment by Mojahed-nour** [comment]
i was able to handle this issue by installing Microsoft MPI v10.0 and then using conda install -c intel mpi4py as explained here (https://stackoverflow.com/a/57781714). Thanks for your kind cooperation.
