### ISSUE TITLE
'Arguments' object has no attribute 'n_proc_per_node'

### ISSUE THREAD

**Issue by royukira** [FedML-AI/FedML#214]
Hi, I am going to run the `mqtt_s3_fedavg_mnist_lr_example` with using GPUs.  I have two computing nodes with 8x A100-GPUs per node. Each machine's environment is :
* Ubuntu LTS 20.04
* CUDA 11.3
* Torch 1.10.0

However, when I tried to run the script `run_server.sh` of `python/examples/cross_silo/mqtt_s3_fedavg_mnist_lr_example`, I encountered a problem about `Arguments' object has no attribute 'n_proc_per_node`. 

* Error: 
```
Traceback (most recent call last):
  File "server/torch_server.py", line 8, in <module>
    fedml.run_cross_silo_server()
  File "/home/fedml/FedML/python/examples/cross_silo/mqtt_s3_fedavg_mnist_lr_example/one_line/../../../../fedml/__init__.py", line 128, in run_cross_silo_server
    device = fedml.device.get_device(args)
  File "/home/fedml/FedML/python/examples/cross_silo/mqtt_s3_fedavg_mnist_lr_example/one_line/../../../../fedml/device/device.py", line 42, in get_device
    args.n_proc_per_node,
AttributeError: 'Arguments' object has no attribute 'n_proc_per_node'
```

My configurations are: 
* fedml_config.yaml (only show the parts I have modified):  
```
train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[1, 2, 3, 4, 5, 6, 7, 8]"
  client_num_in_total: 8
  client_num_per_round: 8
  comm_round: 50
  epochs: 2
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

device_args:
  worker_num: 8
  using_gpu: True
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_config9_2
```

* gpu_mapping.yaml:
```
# 8 clients and 1 server (in compute2) training using 2 machines, each machine has 8 GPUs inside
mapping_config9_2:
    compute2: [0, 0, 0, 0, 2, 1, 1, 1]
    compute1: [0, 0, 0, 0, 1, 1, 1, 1]
```

**Comment by FedML-AI-admin** [comment]
@royukira thanks for the feedback. Currently, we cannot provide the S3 key in the public github. So you can get it back and maintain it at your local. We will replace s3 with https APIs soon.

**Comment by chaoyanghe** [comment]
@Amir-zsh Your hi-fl should not bring issues/arguments to other scenarios like horizontal FL. Please help to fix this issue at
python/examples/cross_silo/mqtt_s3_fedavg_mnist_lr_example

**Comment by chaoyanghe** [comment]
@Amir-zsh I've submitted a fix. please review at: https://github.com/FedML-AI/FedML/commit/7fdf4f65a83fd113d4f87d76ea24c3dfba1900d6

**Comment by chaoyanghe** [comment]
> I have no idea whether the problem is caused by the above modification or `s3`. Could you please help me to solve the problem?
> 
> Thanks for your works.

Please use this configuration as a temporal solution:
https://github.com/FedML-AI/FedML/blob/766706941fdb4757804e008bf03e9f508fdcaaa1/python/examples/cross_silo/mqtt_s3_fedavg_mnist_lr_example/one_line/config/s3_config.yaml


@alex-liang-kh Please update this thread once you finish the https/http APIs for S3 wrapper.

**Comment by royukira** [comment]
> > I have no idea whether the problem is caused by the above modification or `s3`. Could you please help me to solve the problem?
> > Thanks for your works.
> 
> @royukira, Please use this configuration as a temporal solution: https://github.com/FedML-AI/FedML/blob/766706941fdb4757804e008bf03e9f508fdcaaa1/python/examples/cross_silo/mqtt_s3_fedavg_mnist_lr_example/one_line/config/s3_config.yaml
> 
> @alex-liang-kh Please update this thread once you finish the https/http APIs for S3 wrapper.

It works! Thank you very much!
