### ISSUE TITLE
Exception has occurred: AttrbuteError (module 'fedml' has no attribute 'logger'

### ISSUE THREAD

**Issue by trannict** [FedML-AI/FedML#219]
Hi all

Recently,  I am testing SP_FEDAVG_MNIST_LR_CUSTUM_DATA_AND_MODEL_EXAMPLE.

fedml.logger.info("load_data.dataset_name = %s" % args.dataset)

So, I got an errof that has no attribute 'logger'. The problem is at a fedml package or anything else?
![error](https://user-images.githubusercontent.com/104125587/167583485-823938c9-816e-426e-8342-a7b317420e89.png)

Thanks for your comments.

**Comment by chaoyanghe** [comment]
you can just use logging.info to print the log.
