### ISSUE TITLE
FedNAS: Loss comes NaN after 1st round in search.

### ISSUE THREAD

**Issue by garganubhav** [FedML-AI/FedML#23]
Hi, while searching for the darts based fednas code provided, the loss becomes nan and accuracies 0 after the first round. Also, in directly setting stage =train, it gives an error stating tensors expected on cuda :0 but given cuda:5. I have checked but there does not seem to be any bug in the code. What could be wrong in both these setting? Thanks

**Comment by chaoyanghe** [comment]
@garganubhav Hi, this may happen when we transplant FedNAS code from the original github. Could you also test in this github (https://github.com/chaoyanghe/FedNAS) and help to compare this code with FedML?

**Comment by chaoyanghe** [comment]
@garganubhav Hi, have you resolved this issue? May I have more details about your case?
