### ISSUE TITLE
Is there any implements of horizontal federated learning on real world dataset

### ISSUE THREAD

**Issue by emrekapusuzz** [FedML-AI/FedML#230]
Hi, 
I am interested in horizontal federated learning, Can I implement horizontal federated learning on real life datasets?

**Comment by chaoyanghe** [comment]
@emrekapusuzz do you mean customizing the data loader or a new dataset?

**Comment by emrekapusuzz** [comment]
> @emrekapusuzz do you mean customizing the data loader or a new dataset?

Yes, I didn't see any other example about this so I wanted to ask.

**Comment by chaoyanghe** [comment]
@emrekapusuzz yes. you can customize whatever data loader as you like by following the FedMLRunner API. Please check our examples at:

https://github.com/FedML-AI/FedML/tree/master/python/examples

and many applications' implementations at:

https://github.com/FedML-AI/FedML/tree/master/python/app

**Comment by fedml-dimitris** [comment]
The latest FedML version supports many more horizontal Federated Learning applications across various domains as well as in healthcare: https://github.com/FedML-AI/FedML/tree/master/python/app/healthcare.
