### ISSUE TITLE
[FedML CLI] after "start run", we need to provide a new cli for users to check the status of client training.

### ISSUE THREAD

**Issue by chaoyanghe** [FedML-AI/FedML#235]
currently, the user experience is not good since we don't know whether the MLOps has dispatched the client package to the edge device (e.g., MAC OS or linux server)

**Comment by chaoyanghe** [comment]
how about "fedml status"

**Comment by chaoyanghe** [comment]
Users may need to reset the status of the client/server. 

![Image](https://user-images.githubusercontent.com/7238845/171738345-5f16c4ad-2d87-4c57-b3d7-ca9ce8a68218.png)

**Comment by Yvonne-fedml** [comment]
目前fedml status显示的是the current phase of the training
