### ISSUE TITLE
[FedML OSS] [cli] when the server is running (loading data), I started another run, it's stuck there. We should terminate the training whenever we can start another run

### ISSUE THREAD

**Issue by chaoyanghe** [FedML-AI/FedML#242]
We need to terminate the previous process in the client:

![Image](https://user-images.githubusercontent.com/7238845/171749291-b09819c2-d2bb-4daf-b5da-8bc11065c48d.png)

**Comment by chaoyanghe** [comment]
![Image](https://user-images.githubusercontent.com/7238845/171749364-afe416f0-f24d-4bdc-b403-d85fe3e3f9b0.png)

**Comment by alex-liang-kh** [comment]
fixed
