### ISSUE TITLE
[FedML-iot] can't follow the steps in the instruction as some files does not exist

### ISSUE THREAD

**Issue by MIA030399** [FedML-AI/FedML#263]
<img width="815" alt="1655214115(1)" src="https://user-images.githubusercontent.com/57262648/173592511-0b823389-6d0e-422d-ba7b-b6ade2611e14.png">

I am trying to use the FedML-IoT to achieve distributed learning among several edge computing devices. but it always told me that cannot find such a file shown in the above command when I try to follow the given instruction.

This is the instruction:

<img width="460" alt="1655214853(1)" src="https://user-images.githubusercontent.com/57262648/173594531-3423a061-5918-4179-9ee9-2cf85e6ce276.png">

**Comment by leigao97** [comment]
Hi, we are sorry that this README is out of date, and we are transferring this project to [FedML/app/fediot](https://github.com/FedML-AI/FedML/tree/master/app/fediot/nvidia_jetson). Please try the new FedIoT and FedML. Thank you.

**Comment by leigao97** [comment]
Please review the FedML repo and go through the [README](https://github.com/FedML-AI/FedML#installation) at the root directory. You need to install fedml package using pip on both your server and edge devices.
