### ISSUE TITLE
Problem about Fediot

### ISSUE THREAD

**Issue by flying-pigeon** [FedML-AI/FedML#294]
![image](https://user-images.githubusercontent.com/70849115/174307234-2156586a-6996-4d8d-83a0-7d065b2ae1d8.png)
When I'm running torch_client.py, there exists a question related to boto3 and S3. 
How to solve it?

**Comment by chaoyanghe** [comment]
@flying-pigeon may I know which example are you running? or a simple repo for us to reproduce the issue would be helpful. 

If we don't reply timely, please join our slack and ask questions there (find "join the community" at fedml.ai)

**Comment by chaoyanghe** [comment]
@alex-liang-kh you may know the issue and solve it quickly?

**Comment by flying-pigeon** [comment]
> @flying-pigeon may I know which example are you running? or a simple repo for us to reproduce the issue would be helpful.
> 
> If we don't reply timely, please join our slack and ask questions there (find "join the community" at fedml.ai)

the example I'm running is located in the path: FedML-master\app\fediot\anomaly_detection_for_cybersecurity

**Comment by flying-pigeon** [comment]
I'm using the comm way: MQTT_S3. However, it seems that some problems happening in the comm layer of FedML.
I deployed the server and client in the same PC and OS, the client seemed fail to keep a last S3 connection with server. Error is **“_pickle.PicklingError: Can't pickle <class 'botocore.client.S3'>: attribute lookup S3 on botocore.clent failed”**
Furthermore, if I choose MQTT, the error is **"OSError: [WinError 10049] 在其上下文中,该请求的地址无效"**

**Comment by flying-pigeon** [comment]
I'm using the comm way: **MQTT_S3**. However, it seems that some problems happening in the comm layer of FedML.
I deployed the server and client in the same PC and OS, the client seemed fail to keep a last S3 connection with server. Error is **“_pickle.PicklingError: Can't pickle <class 'botocore.client.S3'>: attribute lookup S3 on botocore.clent failed”**
Furthermore, if I choose **MQTT**, the error is **"OSError: [WinError 10049] 在其上下文中,该请求的地址无效"**

**Comment by FedML-AI-admin** [comment]
@leigao97 please check this issue.

**Comment by leigao97** [comment]
Can you describe on what OS you are running fedml and which version of fedml?

**Comment by flying-pigeon** [comment]
I'm running fedml on Windows 10 and the version of fedml is 0.7.90. I've also tried 0.7.0 and 0.7.5, faced with the same problem.
The project I'm running is in&nbsp;&nbsp;FedML-master\app\fediot\anomaly_detection_for_cybersecurity, updated in 17th Jun.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FedML-AI/FedML"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月19日(星期天) 上午8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FedML-AI/FedML] Problem about Fediot (Issue #294)





 
Can you describe on what OS you are running fedml and which version of fedml?

**Comment by flying-pigeon** [comment]
> **FedML-master\app\fediot\anomaly_detection_for_cybersecurity**

I'm running fedml on Windows 10 and the version of fedml is 0.7.90. I've also tried 0.7.0 and 0.7.5, faced with the same problem.
The project I'm running is in  FedML-master\app\fediot\anomaly_detection_for_cybersecurity, updated in 17th Jun.

**Comment by flying-pigeon** [comment]
> Can you describe on what OS you are running fedml and which version of fedml?

I'm running fedml on Windows 10 and the version of fedml is 0.7.90. I've also tried 0.7.0 and 0.7.5, faced with the same problem.
The project I'm running is in  FedML-master\app\fediot\anomaly_detection_for_cybersecurity, updated in 17th Jun.

**Comment by leigao97** [comment]
Hi @flying-pigeon, I tried fedml 0.7.90 and it worked on my desktop. Please join our slack group and we can help you there.

**Comment by flying-pigeon** [comment]
> Hi @flying-pigeon, I tried fedml 0.7.90 and it worked on my desktop. Please join our slack group or wechat group and we can help you there.

I don't know how to join your wechar group. Could you please offer me the QR code?

**Comment by leigao97** [comment]
Please check this link: https://github.com/FedML-AI/FedML#join-the-community

**Comment by flying-pigeon** [comment]
I've scanned the QR code and sent the request. Please accept my friend request.

**Comment by chaoyanghe** [comment]
@flying-pigeon is this issue solved already?

**Comment by fedml-dimitris** [comment]
This issue has been addressed.
