### ISSUE TITLE
develop the Android SDK for FedML-Mobile platform

### ISSUE THREAD

**Issue by FedML-AI-admin** [FedML-AI/FedML#3]

**Comment by chaoyanghe** [comment]
@joyerf Please help this. Put the SDK to Java folder?

**Comment by chaoyanghe** [comment]
@joyerf https://github.com/FedML-AI/FedML/tree/master/mobile/android

**Comment by jlewi** [comment]
@chaoyanghe @joyerf Appreciate all your great work on FedML. 

- What's the current status of Mobile support in FedML? 
- Will the code for Mobile be open sourced and if so is there an ETA?
- How is code packaged and executed on mobile devices? Are you shipping Python code? 
 
I saw a note in https://github.com/FedML-AI/FedML/issues/18#issuecomment-683939678 that the mobile server is ready.

The android directory is empty (https://github.com/FedML-AI/FedML/tree/master/mobile/android). The MLOps [video tutorial](https://doc.fedml.ai/starter/mlops_video.html) however showed it working with Android. So is the code located somewhere else?

I'm trying to understand how FedML compares to [TensorFlow Federated](https://www.tensorflow.org/federated). If I understand correctly TFF uses TensorFlow as a runtime engine so computation gets shipped as TF graphs to be executed in the runtimes.  

It looks like FedML is taking a different approach and shipping Python code. IIUC in the cross-silo use case it uses a docker container as the runtime. What happens in the mobile or IOT case?

**Comment by chaoyanghe** [comment]
> @chaoyanghe @joyerf Appreciate all your great work on FedML.
> 
> * What's the current status of Mobile support in FedML?
> * Will the code for Mobile be open sourced and if so is there an ETA?
> * How is code packaged and executed on mobile devices? Are you shipping Python code?
> 
> I saw a note in [#18 (comment)](https://github.com/FedML-AI/FedML/issues/18#issuecomment-683939678) that the mobile server is ready.
> 
> The android directory is empty (https://github.com/FedML-AI/FedML/tree/master/mobile/android). The MLOps [video tutorial](https://doc.fedml.ai/starter/mlops_video.html) however showed it working with Android. So is the code located somewhere else?
> 
> I'm trying to understand how FedML compares to [TensorFlow Federated](https://www.tensorflow.org/federated). If I understand correctly TFF uses TensorFlow as a runtime engine so computation gets shipped as TF graphs to be executed in the runtimes.
> 
> It looks like FedML is taking a different approach and shipping Python code. IIUC in the cross-silo use case it uses a docker container as the runtime. What happens in the mobile or IOT case?

@jlewi Hi, Thanks for your questions. Our latest Android SDK and IoT platform are released at:

https://github.com/FedML-AI/FedML/tree/master/android

https://github.com/FedML-AI/FedML/tree/master/iot

For more questions, please join our Slack (you can find the link at FedML.ai).
