### ISSUE TITLE
[FedML] [CLI] cannot connect to MQTT and S3 in wireless communication (airline and smartphone) and hospital edge server (higher security level?)

### ISSUE THREAD

**Issue by chaoyanghe** [FedML-AI/FedML#309]
![Image](https://user-images.githubusercontent.com/7238845/176718874-074faf53-3bea-4fba-8383-66964286980e.png)

![Image](https://user-images.githubusercontent.com/7238845/176718886-bbc34cdf-e286-481f-8efb-c075edd105b8.png)

**Comment by arthur-chen0** [comment]
Hi there,
Does this issue solve?
I got the MQTT connection error on my android device running the fedmlsdk_demo app.
![2022-07-20 09-10-29 的螢幕擷圖](https://user-images.githubusercontent.com/68099454/179874649-5e6f3f5a-5048-48e9-9528-416d5c2f90f7.png)
