### ISSUE TITLE
Same error happend when running FEDAVG under STANDALONE just clone the repository without any modification!

### ISSUE THREAD

**Issue by iuserea** [FedML-AI/FedML#34]
When I use commands as below which included in readme.md,
( nohup sh run_fedavg_standalone_pytorch.sh 2 10 64 cifar10 ./../../../data/cifar10 resnet56 homo 200 20 0.001 > ./fedavg_standalone.txt 2>&1
nohup sh run_fedavg_standalone_pytorch.sh 2 10 10 mnist ./../../../data/mnist lr hetero 200 20 0.03 > ./fedavg_standalone.txt 2>&1 &)

The same error occurs:
Traceback (most recent call last):
  File "./main_fedavg.py", line 160, in <module>
    trainer = FedAvgTrainer(dataset, model, device, args)
  File "/home/xx/proj/Source/FedML/fedml_api/standalone/fedavg/fedavg_trainer.py", line 22, in __init__
    self.model_global.train()
AttributeError: 'NoneType' object has no attribute 'train'.

For my poor understanding of PyTorch,can anyone teach me where the code is written not so well?

**Comment by chaoyanghe** [comment]
@iuserea Hi, I think your local code is in an older version. Please update to the latest version. I just double-checked, it works now.

**Comment by chaoyanghe** [comment]
@iuserea check the latest code please.

**Comment by iuserea** [comment]
There're still wrong when running under standalone environment with using following command.

nohup sh run_fedavg_standalone_pytorch.sh 2 10 64 cifar10 ./../../../data/cifar10 resnet56 homo 200 20 0.001 > ./fedavg_standalone.txt 2>&1 &

![image](https://user-images.githubusercontent.com/27194784/96207190-3184c900-0f9d-11eb-914b-e749dd68073f.png)

**Comment by iuserea** [comment]
@chaoyanghe 
Thank you for your kindness for interpretation.I'll have a try at least once.

**Comment by iuserea** [comment]
Something wrong when running following command under standalone environment.
sh run_fedavg_standalone_pytorch.sh 0 10 10 10 mnist ./../../../data/mnist lr hetero 200 20 0.03 sgd 0
@chaoyanghe 

![image](https://user-images.githubusercontent.com/27194784/96666293-645a0300-1389-11eb-9d66-11a80a7a858a.png)
