### ISSUE TITLE
Oops, you failed to login the FedML MLOps platform. Please check whether your network is normal!

### ISSUE THREAD

**Issue by ysrese** [FedML-AI/FedML#343]
Hi all,
I'm testing torch_fedavg_mnist_lr_one_line_example.py with fedml installed.
But I got error like this
<img width="1157" alt="截圖 2022-07-06 01 50 56" src="https://user-images.githubusercontent.com/108757656/177388021-cb6f4a7b-7156-4a2b-9569-11f0747fbae7.png">
Am I missing anything?

Thanks a lot.

**Comment by FedML-AI-admin** [comment]
@ysrese Thanks for your feedback. Please install the latest fedml (0.7.116) and type `fedml env` command and let us know your environment info. An example output is as follows.

```
(fedml3.7) chaoyanghe@Chaoyangs-MacBook-Pro python % fedml env

======== FedML (https://fedml.ai) ========
FedML version: 0.7.116
Execution path:/Users/chaoyanghe/sourcecode/FedML_product/FedML/python/fedml/__init__.py

======== Running Environment ========
OS: Darwin-21.5.0-x86_64-i386-64bit
Hardware: x86_64
Python version: 3.7.13 (default, Mar 28 2022, 07:24:34) 
[Clang 12.0.0 ]
PyTorch version: 1.13.0.dev20220601
MPI4py is installed

======== CPU Configuration ========
The CPU usage is : 50%
Available CPU Memory: 7.4 G / 64.0G

======== GPU Configuration ========
No GPU devices

```

**Comment by FedML-AI-admin** [comment]
If you look the source code, there is no line 308...So please upgrade your library to 0.7.119 and try again.
https://github.com/FedML-AI/FedML/blob/master/python/fedml/mlops/__init__.py

**Comment by ZhuHaipeng7** [comment]
I got this error too. And this error exist after upgrade FedMl to 0.7.119

**Comment by ysrese** [comment]
I got the same error after upgrade fedml to 0.7.119

**Comment by FedML-AI-admin** [comment]
@ZhuHaipeng7 Please also help to run `fedml env`. We are trying to produce this issue.

**Comment by FedML-AI-admin** [comment]
@ZhuHaipeng7 @ysrese we reproduced this issue. I guess you didn't connect internet when you run the script. We will remove this constraint soon, supporting both offline and online training.

**Comment by FedML-AI-admin** [comment]
@ZhuHaipeng7 @ysrese we've resolved this issue. Please upgrade to 0.7.122

**Comment by ZhuHaipeng7** [comment]
> @ZhuHaipeng7 @ysrese we've resolved this issue. Please upgrade to 0.7.122
Thank you. There is no issue after upgrade to 0.7.122.

**Comment by ysrese** [comment]
Thanks a lot!
