### ISSUE TITLE
MNIST datset can't be download by the code!

### ISSUE THREAD

**Issue by weiyikang** [FedML-AI/FedML#35]
I think the download link invalid because I can't find the MNIST data by the link in Chrome.

**Comment by chaoyanghe** [comment]
I checked the downloading in US, it works well. Is it because you cannot access to Google Drive? If not, I guess if it is blocked by GFW. If this is the case, let me put another download link for users in China mainland.

**Comment by weiyikang** [comment]
I can access to the Google Drive, and can download the cifar-10 by the code, while the MNIST is not available by the code.

**Comment by chaoyanghe** [comment]
@weiyikang please pull the latest code, all datasets can be downloaded by script.

**Comment by weiyikang** [comment]
In the latest code, the error also occurs. But I can download the mnist.zip manually by the link in download_and_unzip.sh, then unzip the mnist.zip. The error using 'sh download_and_unzip.sh' as follow:
![image](https://user-images.githubusercontent.com/15953968/95643377-6b5b5880-0ae1-11eb-80a9-c59574ecc677.png)

By manually download mnist.zip and unzip by the guide of download_and_unzip.sh, all going well.

**Comment by chaoyanghe** [comment]
your log shows "Network is unreachable"

**Comment by weiyikang** [comment]
The reason is that computer without vpn can't access the google drive. Baidu yun can be accessed in china instead of google drive.

**Comment by chaoyanghe** [comment]
@weiyikang so please help to create a baidu yun link and a downloading script for our users. Thanks.

**Comment by seanmcneely** [comment]
I am having this issue as well from within the US

**Comment by chaoyanghe** [comment]
@seanmcneely did you download from MAC?

**Comment by seanmcneely** [comment]
I used the download and unzip script for MNIST

**Comment by RaymondTseng** [comment]
Hi @seanmcneely 
You can try the following commands.
```
rm MNIST.zip
rm -rf mnist
wget --no-check-certificate -r "https://drive.google.com/uc?export=download&id=1cU_LcBAUZvfZWveOMhG4G5Fg9uFXhVdf" -O MNIST.zip
unzip MNIST.zip
rm MNIST.zip
```

**Comment by seanmcneely** [comment]
This works! No problems unzipping now.
