### ISSUE TITLE
Network error from wandb

### ISSUE THREAD

**Issue by weiyikang** [FedML-AI/FedML#39]
I want to use the customized model on the customized dataset. **The fedavg can work well on ResNet56 model on our customized dataset.** But the ResNet56 is too big for our small dataset. **So I try to use the small model 'CNN_DropOut' on the fold of 'mode/cv/cnn.py‘.** The problem is the following:
![image](https://user-images.githubusercontent.com/15953968/95815861-36087200-0d50-11eb-9716-efda80072f1a.png)

The model 'CNN_DropOut' can work well on the test_cnn.py as following:
![image](https://user-images.githubusercontent.com/15953968/95816435-af549480-0d51-11eb-92ca-69ae07c0c551.png)

1. Why the network error "ConnectTimeout" happened? The GPUs are available. 
2. Whether the input's shape of CNN_DropOut like (batch_size, channels_num, img_width, img_height)? eg. (32, 3, 28, 28) for mnist dataset.

**Comment by chaoyanghe** [comment]
1. "ConnectTimeout" is a networking issue. It does not have any relationship with the model itself. Please check your network configuration.

2. It depends on the format of PyTorch for convolutional layer. Right, the input parameter format should be (#samples, #channel, width, height).

**Comment by chaoyanghe** [comment]
BTW, the network issue is from the wandb platform. If your network cannot do access to Wandb, it's normal to have this log.

**Comment by weiyikang** [comment]
thx，I will try again with consider the platform of wandb.
