### ISSUE TITLE
Nonsensical if statements

### ISSUE THREAD

**Issue by matech96** [FedML-AI/FedML#40]
Out of curiosity, I let a static code analysis run on the code. It found three nonsensical if statements: [sonarcloud](https://sonarcloud.io/project/issues?id=matech96_FedML&resolved=false&types=BUG).

Maybe sonarcube should be incorporated into the CI process, so we can be notified as these bugs like occur.

**Comment by chaoyanghe** [comment]
@matech96 thanks. Could you help to add it to CI script so that we can automatically find it for our future development.

**Comment by matech96** [comment]
Ok, but someone should register with the FedML-AI github account to [https://sonarcloud.io/](https://sonarcloud.io/)
