### ISSUE TITLE
Question about subgraph division under link prediction task in FedGraphNN

### ISSUE THREAD

**Issue by YoungOGtiger** [FedML-AI/FedML#449]
I have a question about Subgraph-level and Node-level tasks. Under the recommendation systems of a single platform, such as movie recommendation, there is only the rating data of the movie of the user on this platform, which is equivalent to only one type of item, which is movie. Consider the case of croas-device, then each client has only one local user node, multiple item nodes, and edges. At this time, when we expand the client's local Subgraph, we can find the neighbor node and expand it. So is this process more like Node-level tasks?
I read in the paper, Subgraph-level task, Subgraph is divided by: item node category, all item nodes in a category and linked user nodes, which is equivalent to each client having Subgraph data including multiple user nodes, one The client is similar to an organization (with multiple users).
If I want to achieve: A client's initial Subgraph has only one user node and linked item nodes. Then look for the neighbor node, which is the other user node, and then extend the neighbor node and the item node connected to it into the client's Subgraph, so that a client has a user node (only one) and neighbor nodes (possibly multiple) , and the item nodes linked between them, form a updated Subgraph.  Then train.
In this case, we may have a lot of clients, and the way of dividing subgraphs is different from now. Can such a subgraph dividing method be implemented by the existing framework?

**Comment by emirceyani** [comment]
Hello,

It can be, but in a cross-device setting, it is not feasible. This is because we have to copy the model for each user.  However, it is possible to implement partitions specific to the cross-device setting, our setup focuses on the cross-silo setting, and we plan to support the cross-device version of this by developing an efficient partitioning algorithm. Our data is synthetically partitioned.
