### ISSUE TITLE
The parameter of ‘client_num_in_total’ does not work, why fedml set it to 1000 for minist?

### ISSUE THREAD

**Issue by SmILeel** [FedML-AI/FedML#462]
When i tested on 'torch_fedavg_mnist_lr_one_line_example.py', i found that the sampled client_indexes were much larger than the ‘client_num_in_total’  i set in config.yaml file. 
![image](https://user-images.githubusercontent.com/107383023/184352358-e22ba766-223c-40e1-8ec1-ae9f149f9ada.png)
 After checking the source code, i found the 'client_num_in_total' was changed to client_num in fedml.data.MNIST.load_data.py  as follows. This is the same for other datasets like "femnist","shakespeare","fed_shakespeare" and so on.
![image](https://user-images.githubusercontent.com/107383023/184353314-8cebf984-02f3-4542-bfa2-59d14df999b2.png)
![image](https://user-images.githubusercontent.com/107383023/184353602-b36115b0-61a6-4435-a37d-e45fda7322e1.png)
Does it means that the client_num_in_total is unchangable in fedml? We could not modify it for our own setting?  thx.

**Comment by SmILeel** [comment]
train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[1,2,3,4,5]"
  client_num_in_total: 5
  client_num_per_round: 2
  comm_round: 6
  epochs: 3
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
in my yaml file, the client_num_in_total was 5, however, the sampled client_index were 544 and 515 in the first communication round. And my experiments verified that the epochs client_num_per_round  and comm_round worked as my yaml file.

**Comment by SmILeel** [comment]
After checking source code, i found Fedml haven't provide implemented interfaces for  data division and loading. Usersprepare the processed data themselves.

**Comment by SmILeel** [comment]
After checking the source code, I found that fedml does not provide an implementation interface for data segmentation and loading. The user must prepare the processed data by himself.

**Comment by chaoyanghe** [comment]
@SmILeel FedML does provide APIs for data partitions, you can refer to our data loaders at fedml.data and customize your own. For example, check the data loader of `cifar10`, `cifar100`, `cinic10`, when you set the args.client_num_in_total, they will run similar API as `fedml.core.partition_class_samples_with_dirichlet_distribution`. For "femnist","shakespeare","fed_shakespeare", they are synthetic data for pure research, we have to force the client number and other parameters the same as reference paper in NeurIPS, ICML, etc.
