### ISSUE TITLE
Hello, I would like to ask a question about the definition of the two datasets ciao and epinions. 

### ISSUE THREAD

**Issue by YoungOGtiger** [FedML-AI/FedML#464]
Hello, I would like to ask a question about the definition of the two datasets ciao and epinions. Let me first talk about my understanding, do you see it right? Take ciao as an example:
item.dict: index, name (replace with numbers)
user.dict: index, name (replace with numbers)
category.dict: item name, category name (replace with numbers)
graph.txt: user index, item index, rating (equivalent to user rating item)

Because when I looked at graph.txt, I found that data such as 1  1  3 appeared. The user name has 1, but the item name starts from 7375, so I think 1  1 here may be the index, and then 3 points, but I'm not sure if it's right.

Thanks!

**Comment by YoungOGtiger** [comment]
Hello, I would like to ask a question about the partitioning of the ciao dataset.
The first question: There are 28 categories of items in the ciao dataset. If I create 28 clients, does the item representing each client correspond to a category of items? For example, client 0, including items of category 0, and users interacting with it, constitute the local subgraph of client 1.
The second question: the id of the client, does the id of the client correspond to the category of the item, for example: if the current ciao dataset has the 2nd and 10th categories (extracted from the original ciao dataset), then client 0 represents the 2nd category Class item, client 1 represents the 10th class item, is my understanding correct?
Hope to hear back, thanks!

**Comment by YangLiangwei** [comment]
Hi,
For the first question: Your understanding is correct.

For the second question, please refer to #465
