### ISSUE TITLE
Hello, I would like to ask a question about the partitioning of the ciao dataset.

### ISSUE THREAD

**Issue by YoungOGtiger** [FedML-AI/FedML#465]
The first question: There are 28 categories of items in the ciao dataset. If I create 28 clients, does the item representing each client correspond to a category of items? For example, client 0, including items of category 0, and users interacting with it, constitute the local subgraph of client 1.
The second question: the id of the client, does the id of the client correspond to the category of the item, for example: if the current ciao dataset has the 2nd and 10th categories (extracted from the original ciao dataset), then client 0 represents the 2nd category Class item, client 1 represents the 10th class item, is my understanding correct?
Hope to hear back, thanks!

**Comment by YangLiangwei** [comment]
Question 1: If you create 28 clients, each client will hold one category of items with their interactions with users. But the client index and category index may not be the same. We randomly assign each category to each client.

Question 2: In our current version, the index of the client has no relationship with the category's index.

If you think that feature is important, please let us know.

**Comment by fedml-dimitris** [comment]
Issue has been addressed by @YangLiangwei.
