### ISSUE TITLE
Implementing custom ML models

### ISSUE THREAD

**Issue by amyseoj1** [FedML-AI/FedML#474]
Hello, 

Would I be able to run a custom ML model within FedML ?

**Comment by chaoyanghe** [comment]
@amyseoj1 of course. Here are many examples: https://github.com/FedML-AI/FedML/tree/master/examples

For example, you can use CNN, Transformers, GNN like these applications:
https://github.com/FedML-AI/FedML/tree/master/python/app

**Comment by fedml-dimitris** [comment]
Issue already addressed by @chaoyanghe.
