### ISSUE TITLE
which file should I ref to?

### ISSUE THREAD

**Issue by Alan-JW** [FedML-AI/FedML#479]
Hi , which file should I ref to?
![b3e86c7c2e25a3b30f1fc462cec8ebd](https://user-images.githubusercontent.com/74579183/186414449-274ecb6e-35f5-4035-be69-cd5ad7bb6ea5.jpg)

**Comment by chaoyanghe** [comment]
@Alan-JW Hi Alan, sorry for the typo. It means: https://github.com/FedML-AI/FedML/tree/master/python/examples. 

I've submitted this fix. Thanks for your feedback.

**Comment by fedml-dimitris** [comment]
Closing this. The issue has been fixed on the latest FedML docs.
