### ISSUE TITLE
[Shell script] how to handle more than 10 parameters in shell

### ISSUE THREAD

**Issue by QQQHY** [FedML-AI/FedML#48]
It seems that there is a bug with fedml_experiments/standalone/fedavg/run_fedavg_standalone_pytorch.sh, which could cause a parameter passing error.
Probably because  {} for ${10},${11}… is needed when the parameter exceeds 10 (including 10) in the shell.

**Comment by chaoyanghe** [comment]
@QQQHY thanks for your feedback. This depends on the shell implementation. Please check here:
https://stackoverflow.com/questions/4912733/how-to-handle-more-than-10-parameters-in-shell
