### ISSUE TITLE
log file is not saved？

### ISSUE THREAD

**Issue by Alan-JW** [FedML-AI/FedML#481]
Hi， @chaoyanghe.  When I run the “python torch_fedavg_mnist_lr_custum_data_and_model_example.py --cf fedml_config.yaml”, the log file is not saved. Is there a problem with the parameter settings?
![image](https://user-images.githubusercontent.com/74579183/186429681-af12032b-c025-4a75-b9a8-c77c3602d817.png)
![image](https://user-images.githubusercontent.com/74579183/186429521-90ede8c0-5788-4462-b6b9-bc4735946d20.png)

**Comment by chaoyanghe** [comment]
@alex-liang-kh Please have a look at this issue.

**Comment by alex-liang-kh** [comment]
> Hi， @chaoyanghe. When I run the “python torch_fedavg_mnist_lr_custum_data_and_model_example.py --cf fedml_config.yaml”, the log file is not saved. Is there a problem with the parameter settings? ![image](https://user-images.githubusercontent.com/74579183/186429681-af12032b-c025-4a75-b9a8-c77c3602d817.png) ![image](https://user-images.githubusercontent.com/74579183/186429521-90ede8c0-5788-4462-b6b9-bc4735946d20.png)

@Alan-JW  log files are in the following diretory: ~/fedml-client/fedml/logs and ~/fedml-server/fedml/logs

**Comment by Alan-JW** [comment]
Thanks, i found it.

**Comment by chaoyanghe** [comment]
@Alan-JW I've removed this argument to avoid confusion. We don't need users to set it in the latest version.
