### ISSUE TITLE
Error when running  ‘run_custom_data_and_model_example.sh’

### ISSUE THREAD

**Issue by Alan-JW** [FedML-AI/FedML#486]
Hi, @chaoyanghe, I encountered the following error when running ‘run_custom_data_and_model_example.sh’, but I have torch installed？
![image](https://user-images.githubusercontent.com/74579183/186681717-dc91e4d9-7d1f-439a-bbf4-b15b3c7bca6b.png)
![image](https://user-images.githubusercontent.com/74579183/186681901-8152e3ee-3cc9-4714-8035-9423012cc6b0.png)

**Comment by chaoyanghe** [comment]
@Alan-JW have you tried a simple PyTorch demo? or
```
(base) chaoyanghe@Chaoyangs-MBP FedML_product % python
Python 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> 

```

If these two also raised errors, it's not related to FedML. You then need to search at stackoverflow for further help.

**Comment by Alan-JW** [comment]
@chaoyanghe 
![image](https://user-images.githubusercontent.com/74579183/186730842-36429f94-0a5d-47bb-91e5-c1d0b8c5558f.png)

**Comment by chaoyanghe** [comment]
@Alan-JW how about this one?
python/examples/simulation/sp_fedavg_mnist_lr_example

**Comment by chaoyanghe** [comment]
@Alan-JW please join our slack or discord (you can find the link at fedml.ai), and let's follow more details there.

**Comment by Alan-JW** [comment]
@chaoyanghe 
![image](https://user-images.githubusercontent.com/74579183/186737295-558b5c97-b1cf-4f2c-adfc-d04414315220.png)


> @Alan-JW please join our slack or discord (you can find the link at fedml.ai), and let's follow more details there.

Ok

**Comment by fedml-dimitris** [comment]
Closing this. The issue has been resolved.
