### ISSUE TITLE
Errors in downloading datasets from Google Drive

### ISSUE THREAD

**Issue by prosopher** [FedML-AI/FedML#49]
I recommend the data manager to move datasets in Google Drive to other data repository for the following errors.

- 'Quota exceeded' error
Whiled executing 'CI-install.sh', I have encountered 'qouta exceeded' error for some dataset files from Google Drive, which produced an incomplete 'h5' files and caused a CI failure.
The files may be locked for a 24 hour period before the quota is reset. [[link]](https://www.geekrar.com/fix-bypass-google-drive-download-limit-error/#:~:text=What's%20Google%20Drive%20Download%20Limit%20(Quota%20Exceeded),-Generally%2C%20everyone%20is&text=For%20instance%2C%20if%20a%20large,when%20the%20availability%20limit%20reaches.&text=The%20period%20the%20file%20is,t%20continue%20receiving%20high%20traffic.)

- 'Virus scan warning' error
For 'sh download_federatedEMNIST.sh' command in 'CI-install.sh', I have encountered another type of error, which produced an incomplete 'emnist_test.h5' that contained:
> <!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><link href=&#47;static&#47;doclist&#47;client&#47;css&#47;148676949&#45;untrustedcontent.css rel="stylesheet"><link rel="icon" href="https://ssl.gstatic.com/docs/doclist/images/infinite_arrow_favicon_4.ico"/><style nonce="SBJBwuBjbn6MgL9cqdTcug">#gbar,#guser{font-size:13px;padding-top:0px !important;}#gbar{height:22px}#guser{padding-bottom:7px !important;text-align:right}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;top:24px;width:100%}@media all{.gb1{height:22px;margin-right:.5em;vertical-align:top}#gbar{float:left}}a.gb1,a.gb4{text-decoration:underline !important}a.gb1,a.gb4{color:#00c !important}.gbi .gb4{color:#dd8e27 !important}.gbf .gb4{color:#900 !important}</style><script nonce="SBJBwuBjbn6MgL9cqdTcug"></script></head><body><div id=gbar><nobr><a target=_blank class=gb1 href="https://www.google.co.kr/webhp?tab=ow">Search</a> <a target=_blank class=gb1 href="http://www.google.co.kr/imghp?hl=en&tab=oi">Images</a> <a target=_blank class=gb1 href="https://maps.google.co.kr/maps?hl=en&tab=ol">Maps</a> <a target=_blank class=gb1 href="https://play.google.com/?hl=en&tab=o8">Play</a> <a target=_blank class=gb1 href="https://www.youtube.com/?gl=KR&tab=o1">YouTube</a> <a target=_blank class=gb1 href="https://news.google.com/?tab=on">News</a> <a target=_blank class=gb1 href="https://mail.google.com/mail/?tab=om">Gmail</a> <b class=gb1>Drive</b> <a target=_blank class=gb1 style="text-decoration:none" href="https://www.google.co.kr/intl/en/about/products?tab=oh"><u>More</u> &raquo;</a></nobr></div><div id=guser width=100%><nobr><span id=gbn class=gbi></span><span id=gbf class=gbf></span><span id=gbe></span><a target="_self" href="/settings?hl=en_US" class=gb4>Settings</a> | <a target=_blank  href="//support.google.com/drive/?p=web_home&hl=en_US" class=gb4>Help</a> | <a target=_top id=gb_70 href="https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://docs.google.com/uc%3Fexport%3Ddownload%26confirm%3D1u%26id%3D1wUzroOnlArzcFe8MT-PKI1jgubfLuTfd&service=writely&ec=GAZAMQ" class=gb4>Sign in</a></nobr></div><div class=gbh style=left:0></div><div class=gbh style=right:0></div><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption"><span class="uc-name-size"><a href="https://docs.google.com/open?id=1wUzroOnlArzcFe8MT-PKI1jgubfLuTfd">emnist_test.h5</a> (233M)</span> is too large for Google to scan for viruses. Would you still like to download this file?</p><a id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" href="/uc?export=download&amp;confirm=Rb8p&amp;id=1wUzroOnlArzcFe8MT-PKI1jgubfLuTfd">Download anyway</a></div></div><div class="uc-footer"><hr class="uc-footer-divider">&copy; 2020 Google - <a class="goog-link" href="//support.google.com/drive/?p=web_home">Help</a> - <a class="goog-link" href="//support.google.com/drive/bin/answer.py?hl=en_US&amp;answer=2450387">Privacy & Terms</a></div></body></html>

**Comment by chaoyanghe** [comment]
@prosopher Hi Thanks for this message. We also met this issue previously. We plan to buy AWS cloud service to support this later.
