### ISSUE TITLE
Problem in trying Octopus example

### ISSUE THREAD

**Issue by IWTF** [FedML-AI/FedML#527]
I run into a problem when I try Octopus examples.
I can not execute the command, `fedml build -t server -sf $SOURCE -ep $ENTRY -cf $CONFIG -df $DEST`.
The Error is `fedml: command not found`

**Comment by chaoyanghe** [comment]
@IWTF Hi, please follow the guidance at https://doc.fedml.ai/starter/installation.html

if you met any issues, please report the results of "fedml env" command.

**Comment by IWTF** [comment]
thank you! the problem is sloved
