### ISSUE TITLE
Installation encountered multiple errors

### ISSUE THREAD

**Issue by MING-LI-JIANG** [FedML-AI/FedML#530]
The first error encountered is : 
```
Building wheels for collected packages: fedml
  Building wheel for fedml (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1027 lines of output]
```
The second error : 
```
error: could not create 'build\bdist.win-amd64\wheel\fedml-0.7.305.data\purelib\examples\cross_silo\mqtt_s3_fedavg_hierarchical_manual_mnist_lr_example\one_line\main_fedml_cross_silo_hi.py': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fedml
  Running setup.py clean for fedml
Failed to build fedml
```
The last message displayed is : 
```
DEPRECATION: fedml was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issues/8368
```
The installation steps are all installed in accordance with the [FEDML INSTALLATION ON WINDOWS OS](https://doc.fedml.ai/starter/install/windows.html) teaching, also tried using older versions of python (eg: 3.7, 3.9), but still got the same problem.

**Comment by chaoyanghe** [comment]
@MING-LI-JIANG we've tested windows compatibility a lot. Maybe your environment is not covered in our test cases. We are interested in solving your issues. Please join our slack and discuss more details (find the link at https://fedml.ai).

**Comment by chaoyanghe** [comment]
@alex-liang-kh

**Comment by alex-liang-kh** [comment]
@MING-LI-JIANG ， What is your Windows OS version？

**Comment by MING-LI-JIANG** [comment]
@alex-liang-kh , My Windows version is : 
```
Edition     Windows 11Pro for Workstations
Version     21H2
OS build    22000.918
Experience  Windows Feature Experience Pack 1000.22000.918.0
```

**Comment by chaoyanghe** [comment]
@MING-LI-JIANG have you tried the latest version 0.7.312?

**Comment by MING-LI-JIANG** [comment]
Hello, I have installed the latest version of fedml-0.7.315, but the error still occurs.
    在 2022年9月7日 星期三 上午05:00:44 [GMT+8]， Chaoyang ***@***.***> 寫道：  
 
 


@MING-LI-JIANG have you tried the latest version 0.7.312?

**Comment by MING-LI-JIANG** [comment]
@chaoyanghe 
Also tried to install version 0.7.312, but it still doesn't work.
Among those errors I found a link (https://github.com/pypa/pip/issues/8368), I don't know if it is related to this message??

**Comment by alex-liang-kh** [comment]
@MING-LI-JIANG  You may try to install new version 0.7.316: pip install fedml.

**Comment by MING-LI-JIANG** [comment]
@alex-liang-kh The new version (version: 0.7.319) has no errors, many thanks to the FedML team for their assistance.
