### ISSUE TITLE
Hello, I want to use the Krum algorithm in fedml. I changed part of the code. Can you help me see if this is correct?

### ISSUE THREAD

**Issue by JessKXWL** [FedML-AI/FedML#531]
First,Create fedmldefender using singleton mode.
![image](https://user-images.githubusercontent.com/33014711/188412169-c297de3a-6404-4524-880a-a208a65b0605.png)

Then, Add Krum to the defense method.
![image](https://user-images.githubusercontent.com/33014711/188412527-d177262e-712b-4f6f-b663-56f5e5ce3d23.png)

Finally, modify Krum_ The code in defense.py is as follows:
```
class KrumDefense(BaseDefenseMethod):
    def __init__(self, config):
        self.config = config
        self.k = config.byzantine_client_num  # assume there are k byzantine clients
        if config.multi:
            self.multi = False
        else:
            self.multi = config.multi  # krum or multi-krum
    def run(
            self,
            raw_client_grad_list: List[Tuple[float, Dict]],
            base_aggregation_func: Callable = None,
            extra_auxiliary_info: Any = None,
    ):
        model_list = self.defend_before_aggregation(
            raw_client_grad_list=raw_client_grad_list,
            extra_auxiliary_info=extra_auxiliary_info,
        )
        return self.defend_on_aggregation(
            raw_client_grad_list=model_list,
            base_aggregation_func=base_aggregation_func,
            extra_auxiliary_info=extra_auxiliary_info,
        )
    #
    def _compute_krum_score(self, local_w):
        krum_score = []
        num_client = len(local_w)
        for i in range(0, num_client):
            dists = []
            for j in range(0, num_client):
                # i and j distance |pi-pj|^2
                if i != j:
                    dists.append(utils.compute_euclidean_distance(local_w[i][1], local_w[j][1]).item())
            dists.sort()
            score = dists[0: num_client - self.k]
            krum_score.append(sum(score))
        return krum_score
    #
    def defend_before_aggregation(
            self,
            raw_client_grad_list: List[Tuple[float, Dict]],
            extra_auxiliary_info: Any = None,
    ):

        num_client = len(raw_client_grad_list)
        vec_local_w = [
            (raw_client_grad_list[i][0], utils.vectorize_weight(raw_client_grad_list[i][1]))
            for i in range(0, num_client)
        ]
        print(vec_local_w)
        krum_score = self._compute_krum_score(vec_local_w)
        index = torch.argsort(torch.Tensor(krum_score)).tolist()
        if self.multi is True:
            index = index[0:num_client - self.k]
        else:
            index = index[0:1]

        grad_list = [raw_client_grad_list[i] for i in index]
        print(f"krum_scores = {krum_score}")
        return grad_list

    def defend_on_aggregation(
            self,
            raw_client_grad_list: List[Tuple[float, Dict]],
            base_aggregation_func: Callable = None,
            extra_auxiliary_info: Any = None,
    ):
        avg_params = base_aggregation_func(self.config, grad_list)
        return avg_params
```

**Comment by chaoyanghe** [comment]
@han-shanshan please help to follow this issue.

**Comment by han-shanshan** [comment]
Hi, 
Please pull the latest code (fedml v0.7.310), and find examples at examples/cross_silo/mqtt_s3_fedavg_defense_mnist_lr_example. We support Krum and MultiKrum (config file: examples/cross_silo/mqtt_s3_fedavg_defense_mnist_lr_example/config/krum/fedml_config.yaml, examples/cross_silo/mqtt_s3_fedavg_defense_mnist_lr_example/config/multikrum/fedml_config.yaml). The default example is using foolsgold defense. To run krum, you only need to change the folder name in run_server.sh and run_client.sh to krum, and follow instructions in README. If you have any other questions, feel free to leave your wechat so that we can answer your questions immediately. 
Thanks.

**Comment by JessKXWL** [comment]
This is my wechat，either1998，I still have some questions and I need your help with.-------- 原始邮件 --------发件人： shanshan ***@***.***>日期： 2022年9月6日周二 下午1:33收件人： FedML-AI/FedML ***@***.***>抄送： JessKXWL ***@***.***>, Author ***@***.***>主    题： Re: [FedML-AI/FedML] Hello, I want to use the Krum algorithm in fedml. I changed part of the code. Can you help me see if this is correct? (Issue #531)
Hi,
Please pull the latest code (fedml v0.7.310), and find examples at examples/cross_silo/mqtt_s3_fedavg_defense_mnist_lr_example. We support Krum and MultiKrum (config file: examples/cross_silo/mqtt_s3_fedavg_defense_mnist_lr_example/config/krum/fedml_config.yaml, examples/cross_silo/mqtt_s3_fedavg_defense_mnist_lr_example/config/multikrum/fedml_config.yaml). The default example is using foolsgold defense. To run krum, you only need to change the folder name in run_server.sh and run_client.sh to krum, and follow instructions in README. If you have any other questions, feel free to leave your wechat so that we can answer your questions immediately.
Thanks.

**Comment by yzgrfsy** [comment]
@han-shanshan,  thank you for your contribution . when i run the krum,i find that some files is  mising in krum  folder ,for example: 
1 )config/gpu_mapping.yaml,
2)grpc_ipconfig_path: ./config/grpc_ipconfig.csv,3)mqtt_config_path:
  4) s3_config_path:  I don't know if it's necessary.  when i run foolsgold ,it don't work again ,Shows the following error:
![image](https://user-images.githubusercontent.com/20572899/189075100-c1e359a6-afa5-4ea6-add6-56e5ee899238.png)

**Comment by han-shanshan** [comment]
@yzgrfsy Sorry for the late reply. Please pull the latest code. We've added gpu_mapping.yaml. If you want to run krum using gpu, you only need to set using_gpu to true. In fedml_config.yaml, the client number per round and worker number are set to 10 by default. If you want to change the number, you need to change gpu_mapping_key in fedml_config.yaml according to gpu_mapping.yaml. 
Thanks.
