### ISSUE TITLE
Use custom ClientTrainer in sp simulation? 

### ISSUE THREAD

**Issue by doshik** [FedML-AI/FedML#565]
I see in the code base that `FedMLRunner` accepts a `ClientTrainer` as an optional argument. However, even after defining custom trainer I can see that the code does not pass my trainer to the simulator and instead uses a default trainer. Why is this? Thanks for your help. 
<img width="879" alt="image" src="https://user-images.githubusercontent.com/12504230/189419749-310d3e14-d2cc-463d-8f51-d9a7543445f8.png">

**Comment by doshik** [comment]
I fixed this by making the change manually.

**Comment by chaoyanghe** [comment]
@doshik great. Please hep to PR your changes
