### ISSUE TITLE
Errors encountered when using different machine learning engines.

### ISSUE THREAD

**Issue by MING-LI-JIANG** [FedML-AI/FedML#576]
Using TensorFlow, Jax, and MXNet machine learning engine still encounter the following error when installing:
```
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.1-py3-none-any.whl (151 kB)
Building wheels for collected packages: h5py
  Building wheel for h5py (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      C:\Users\icmnlab-user\anaconda3\envs\fedml2\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\h5py
```

```
      running build_ext
      error: Could not find module 'hdf5.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      Loading library to get version: hdf5.dll
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
  Running setup.py clean for h5py
Failed to build h5py
```

```
ERROR: Could not find a version that satisfies the requirement jaxlib; extra == "jax" (from fedml[jax]) (from versions: none)
ERROR: No matching distribution found for jaxlib; extra == "jax"
```

```
ERROR: Could not find a version that satisfies the requirement mxnet==2.0.0b1; extra == "mxnet" (from fedml[mxnet]) (from versions: 0.11.0, 0.12.0, 0.12.1, 1.0.0, 1.0.0.post1, 1.0.0.post3, 1.0.0.post4, 1.1.0.post0, 1.2.0, 1.2.1, 1.2.1.post1, 1.3.0, 1.3.1, 1.4.0, 1.4.0.post0, 1.4.1, 1.5.0, 1.6.0, 1.7.0.post1, 1.7.0.post2)
ERROR: No matching distribution found for mxnet==2.0.0b1; extra == "mxnet"
```
I would like to ask if this is caused by the lack of software I installed?

**Comment by alex-liang-kh** [comment]
1. You should install tensorflow lib by the following commands:
pip install fedml[tensorflow]
2. Your should install jax lib by the following command:
1) On Linux and MacOS platform:
  pip install fedml[jax]
2) On Windows platform:
  pip install jaxlib -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver
  pip install fedml[jax]
3. Your should install mxnet lib by the following command:
1) On Linux and MacOS x86 platform:
   pip install fedml[mxnet]
2) On Windows and Mac M1 platform, you should build mxnet lib from source:
   [https://mxnet.apache.org/get_started/build_from_source](https://mxnet.apache.org/get_started/build_from_source)

**Comment by alex-liang-kh** [comment]
@MING-LI-JIANG , On Windows platform, maybe you need to do extra installation steps, you may run installation based the following guidances:

1. You should install tensorflow lib by the following commands:
pip install fedml[tensorflow]

2. Your should install jax lib by the following command:
(1) On Linux and MacOS platform:
pip install fedml[jax]
(2) On Windows platform:
pip install jaxlib -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver
pip install fedml[jax]

3. Your should install mxnet lib by the following command:
(1) On Linux and MacOS x86 platform:
pip install fedml[mxnet]
(2) On Windows and Mac M1 platform, you should build mxnet lib from source:
https://mxnet.apache.org/get_started/build_from_source

**Comment by fedml-dimitris** [comment]
Closing this since @fedml-alex has already addressed the issue.
