### ISSUE TITLE
terminology in run_vfl_fc_two_party_lending_club.py

### ISSUE THREAD

**Issue by peiji1981** [FedML-AI/FedML#61]
hello, i may find a mistake in run_vfl_fc_two_party_lending_club.py . only  party_a has label  , so party_a may be host not guest ?

**Comment by chaoyanghe** [comment]
@yankang18 Hi Yan Kang, please help to check whether this is an error.

**Comment by yankang18** [comment]
@peiji1981 In the current vertical federated learning setting, only party A has labels. Other parties only provide features for building the federated model.

The guest typically refers to the party that has an application scenario such as loan lending (it has labels) but it lacks data (e.g., features) to build a good prediction model.
The host typically refers to the data provider that offers rich data (e.g. features) for helping guests to build machine learning models.

**Comment by peiji1981** [comment]
> @peiji1981 In the current vertical federated learning setting, only party A has labels. Other parties only provide features for building the federated model.
> 
> The guest typically refers to the party that has an application scenario such as loan lending (it has labels) but it lacks data (e.g., features) to build a good prediction model.
> The host typically refers to the data provider that offers rich data (e.g. features) for helping guests to build machine learning models.

Thx, buddy . But this setting may be confused. Generally, the host has label

**Comment by chaoyanghe** [comment]
> > @peiji1981 In the current vertical federated learning setting, only party A has labels. Other parties only provide features for building the federated model.
> > The guest typically refers to the party that has an application scenario such as loan lending (it has labels) but it lacks data (e.g., features) to build a good prediction model.
> > The host typically refers to the data provider that offers rich data (e.g. features) for helping guests to build machine learning models.
> 
> Thx, buddy . But this setting may be confused. Generally, the host has label

So the code is correct. It doesn't matter how to call one of the parties.

**Comment by yankang18** [comment]
@peiji1981 

Different scenarios may use different terminology. To avoid confusion, we may use a more neutral name for the host and guest.

**Comment by chaoyanghe** [comment]
@yankang18 how about drawing a diagram to illustrate our current implementation?

**Comment by peiji1981** [comment]
> @yankang18 how about drawing a diagram to illustrate our current implementation?

hello, Dr.He， can you share a link for download the lendingclub dataset , the previous link did not conclude the data

**Comment by fedml-dimitris** [comment]
Closing this issue, since it is not related to a problem of the FedML library but rather to how to tackle a vertical federated learning setting.
