### ISSUE TITLE
After few communication round, client and server are losing the connection (fedcv/object_detection)

### ISSUE THREAD

**Issue by Adeelbek** [FedML-AI/FedML#630]
I was using FedML platform for testing distributed training results for object detection between single server and multiple clients. 
Unfortunately, MQTT has some issue where server or client sometimes cannot receive the packet properly and showing only:

 ```
receive_message. msg_type = 0, sender_id = 0, receiver_id = 0
receive_message. msg_type = 0, sender_id = 0, receiver_id = 0
```
where ``` msg_type = 0 ``` means received message has been corrupted. Although, I am using one server with multiple GPU to simulate 
server and clients based distributed training ```CROSS_SILO_HORIZONTAL``` mode, I could not understand why is this happening. Especially, when i use bigger data, this problem is happening in very early  communication rounds. 

So, if anyone has solution with this problem, please share your experience. 

Just in case, I am attaching output of server and clients screenshots. 

``` SERVER OUTPUT```
![server_output](https://user-images.githubusercontent.com/25815077/198559962-b707674f-177a-402b-b951-85cbfff14d5f.png)

``` CLIENT-1 OUTPUT ```
![client_output](https://user-images.githubusercontent.com/25815077/198560198-c8215b1a-7178-44f0-8518-bf2499686c50.png)

``` CLIENT-2 OUTPUT```
![client2_output](https://user-images.githubusercontent.com/25815077/198560287-00ce1e46-7840-48d6-8ba7-7d0de8606dae.png)

**Comment by SuperXxts** [comment]
> I was using FedML platform for testing distributed training results for object detection between single server and multiple clients. Unfortunately, MQTT has some issue where server or client sometimes cannot receive the packet properly and showing only:
> 
> ```
> receive_message. msg_type = 0, sender_id = 0, receiver_id = 0
> receive_message. msg_type = 0, sender_id = 0, receiver_id = 0
> ```
> 
> where `msg_type = 0` means received message has been corrupted. Although, I am using one server with multiple GPU to simulate server and clients based distributed training `CROSS_SILO_HORIZONTAL` mode, I could not understand why is this happening. Especially, when i use bigger data, this problem is happening in very early communication rounds.
> 
> So, if anyone has solution with this problem, please share your experience.
> 
> Just in case, I am attaching output of server and clients screenshots.
> 
> ` SERVER OUTPUT` ![server_output](https://user-images.githubusercontent.com/25815077/198559962-b707674f-177a-402b-b951-85cbfff14d5f.png)
> 
> `CLIENT-1 OUTPUT` ![client_output](https://user-images.githubusercontent.com/25815077/198560198-c8215b1a-7178-44f0-8518-bf2499686c50.png)
> 
> ` CLIENT-2 OUTPUT` ![client2_output](https://user-images.githubusercontent.com/25815077/198560287-00ce1e46-7840-48d6-8ba7-7d0de8606dae.png)

I have found a similar problem in #623

**Comment by chaoyanghe** [comment]
@Adeelbek @SuperXxts Please join our slack channel #fedml-app-object-detection for more detailed and efficient discussion.

**Comment by HoTuanLong** [comment]
@chaoyanghe @Adeelbek @SuperXxts Does anyone have any solution for this? I am still facing this problem?
Thanks!

**Comment by Adeelbek** [comment]
> 

The solution is to just avoid using the MQTT-S3 protocol. Use any other protocol, like gRPC or MPI. In my case, I am getting around this problem by just using gRPC. 

See this example for how to use gRPC :
```FedML/tree/master/python/examples/cross_silo)/grpc_fedavg_mnist_lr_example/```

**Comment by HoTuanLong** [comment]
@Adeelbek I tried gRPC, but my server returned "Connection not ready for {client_id}".

**Comment by Adeelbek** [comment]
```"Connection not ready for {client_id}"``` this message is normal operation. The server waits till it receives a connection request from all clients that you defined in your ```fedm_config.yaml``` file. Once it receives messages from all the clients, then it lets clients start their training. Do an extra check-up of your configuration file. Make sure your local host IP addresses are correct and ids are not duplicated. Also, make sure u have only one server with the same id and IP runinng on your system.
