### ISSUE TITLE
Suggestion: wrapping shell parameters with {} in experiments/run_xxx.sh

### ISSUE THREAD

**Issue by ProgramSalamander** [FedML-AI/FedML#65]
Hi,

I have installed FedML on my MacOS and tried to run the standalone fedavg experiment locally.

when i input this command:
```
sh run_fedavg_standalone_pytorch.sh 0 2 2 4 mnist ./../../../data/mnist lr hetero 1 1 0.03 sgd 1
```
I got this error:
```
Traceback (most recent call last):
  File "./main_fedavg.py", line 258, in <module>
    trainer.train()
  File "/Users/xuyangchen/Developer/PycharmProjects/FedML/fedml_api/standalone/fedavg/fedavg_trainer.py", line 71, in train
    w, loss = client.train(w_global)
  File "/Users/xuyangchen/Developer/PycharmProjects/FedML/fedml_api/standalone/fedavg/client.py", line 76, in train
    return self.model.cpu().state_dict(), sum(epoch_loss) / len(epoch_loss)
ZeroDivisionError: division by zero
```
And i found the problems occurs since the parameter for `epochs` does not actually captured:
```
INFO:root:Namespace(batch_size=4, ci=3, client_num_in_total=2, client_num_per_round=2, client_optimizer='02', comm_round=1, data_dir='./../../../data/mnist', dataset='mnist', epochs=0, frequency_of_the_test=5, gpu=0, lr=1.0, model='lr', partition_alpha=0.5, partition_method='hetero', wd=0.001)
```

The reason turns to be that parameters that after $9 were not wrapped with `{}` in `fedml_experiments/standalone/fedavg/run_fedavg_standalone_pytorch.sh` 
```
EPOCH=$10

LR=$11

OPT=$12

CI=$13
```
after I wrapped them and got the experiment run successfully.
```
EPOCH=${10}

LR=${11}

OPT=${12}

CI=${13}
```

Maybe it has been working well on Linux, but I still suggest that these parameters (may also found in other `run_xxx.sh`) can be "improved".

Btw, this is really a great project for researchers, thanks to all contributors :)

**Comment by chaoyanghe** [comment]
Thanks. Please refer to this link: https://github.com/FedML-AI/FedML/issues/48
