### ISSUE TITLE
The error in new machine when running distribution/fedavg

### ISSUE THREAD

**Issue by weiyikang** [FedML-AI/FedML#68]
I think the FedML can use easily on another machine only by cloning the FedML without modifications. While the errors occur as follows:

Configures of computer:
1. 4 * RTX 3090, cuda 11.1
2. pytorch1.7
3. According to CI-install.sh requiring the environment

run the command:
sh run_fedavg_distributed_pytorch.sh 4 4 1 4 cnn homo 2 1 32 0.0001 digit5 "./../../../data/Digit5" 0
There are 4 clients and 4 works.

The errors as follows(Fig.1 the warning of program, Fig.2 the 4 clients on GPUs may be wrong, the same process on all GPUs):

![image](https://user-images.githubusercontent.com/15953968/100110968-8b37b780-2ea8-11eb-8329-9f5207ff443c.png)

![image](https://user-images.githubusercontent.com/15953968/100107923-27f85600-2ea5-11eb-8206-d6607eb4c6db.png)

**Comment by chaoyanghe** [comment]
are you using the same version of the code? We updated a lot recently.

**Comment by weiyikang** [comment]
I used the previous version, I will try the latest version again.

**Comment by weiyikang** [comment]
I have used the latest version, FedAvg(distribution) on 4 * RTX3090 computer as shown in Fig.1, while the previous version on 8 * RTX2080 as shown in Fig.2. Why there exist many 0MiB FedAvg(distributed) in the latest version? Can I only use the specified GPUs such as gpu:0, gpu:2 because there are other users on the same computer?

![image](https://user-images.githubusercontent.com/15953968/100177159-7f7ddc80-2f0c-11eb-8c35-f8ca0cacb4ae.png)

![image](https://user-images.githubusercontent.com/15953968/100177806-b6a0bd80-2f0d-11eb-90c2-27193e4eae63.png)

**Comment by chaoyanghe** [comment]
May I know how you set your "init_training_device" function?
