### ISSUE TITLE
A problem with load_synthetic_data function

### ISSUE THREAD

**Issue by weizj0328** [FedML-AI/FedML#765]
There is a reference to the load_synthetic_data function in fedcv/object_detection/data/data_loader_cross_silo.py, as shown below:
![1](https://user-images.githubusercontent.com/73020982/218075508-6d9d2af3-646c-47c4-930c-80c5b3caf6b7.png)
But there is no definition of this function in the data_loader.py file in the same directory.

**Comment by fedml-dimitris** [comment]
@weizj0328 Closing this since it will be addressed here:
https://github.com/FedML-AI/FedML/issues/765
