### ISSUE TITLE
standalone Benchmark running the MNIST and Shakespeare

### ISSUE THREAD

**Issue by sjtu-cz** [FedML-AI/FedML#79]
I can not get the same results when I run the command:
sh run_fedavg_standalone_pytorch.sh 0 10 10 10 shakespeare ./../../../data/shakespeare rnn hetero 100 1 0.8 sgd 0
my results is:
https://wandb.ai/pilgrim_cz/fedml/runs/5jqpw1i4?workspace=user-pilgrim_cz
the benchmart res is https://wandb.ai/automl/fedml/runs/144ey9w6
same problem when I run minst dataset
Is there anything wrong? I did not change any code.

**Comment by Elliebababa** [comment]
Hi, the link you provide is not accessible. And we have updated the code recently. Did you run the most updated code? Or you can provide more information so that we can help.

**Comment by sjtu-cz** [comment]
![Uploading image.png…]()

**Comment by sjtu-cz** [comment]
![image](https://user-images.githubusercontent.com/20858982/102304918-9ce91800-3f99-11eb-8a4a-092852a33eac.png)

**Comment by sjtu-cz** [comment]
ok, I will test the most updated code later,  updated 7 hours ago ?

**Comment by Elliebababa** [comment]
Yes, please have a try.

**Comment by chaoyanghe** [comment]
@sjtu-cz thanks for your feedback. What's your git version?
Please let us know your results based on the latest code.

**Comment by sjtu-cz** [comment]
The results are correct now,  the problem is caused by parameter passing error  in FedML/fedml_experiments/standalone/fedavg/run_fedavg_standalone_pytorch.sh   
EPOCH=$10  => EPOCH=${10} ... 
This is a small problem，the former epoch is always 0， so the result is not correct.

**Comment by chaoyanghe** [comment]
@sjtu-cz Great! Happy to know you can reproduce the result.

**Comment by am009** [comment]
I encountered same problem today. 😭 The error in the script still exists. I really hope it can be corrected so that other people will not meet the same problem again.
I opened a pull request at https://github.com/FedML-AI/FedML/pull/180 . Hope it's helpful.

Related link:
https://stackoverflow.com/questions/4912733/how-to-handle-more-than-10-parameters-in-shell
