### ISSUE TITLE
MLops Model Serving Bugs

### ISSUE THREAD

**Issue by Raphael-Jin** [FedML-AI/FedML#858]
1. When the Endpoint requires a dynamic input shape, the UI presents nothing.

![Image](https://user-images.githubusercontent.com/40858699/229927206-f2b22b76-589f-4a03-97a3-8d81bbfff22b.png)

this is caused by the undetermined input shape, to Fix this one can assume the batch size defaults to 1.

2. When a user want to updated Model, the User has to go to Inference EndPoint -> Name Endpoint, 
if they choose the same name of their previous Endpoint, even the model version is different, the system raise "Created Failed" Exception.

Solution: Endpoint name is unique.

![Image](https://user-images.githubusercontent.com/40858699/229932711-f424b4de-0f44-4edb-b282-b7b8ef9d7d62.png)

3. When User Click Model Card -> Click a Model -> Click "Source code and Configuration", it gives a error

Solution: Determine whether the model is from open

![Image](https://user-images.githubusercontent.com/40858699/229930288-8334ab6f-d4a8-44be-8dc3-4fab600e54b6.png)

4. When User Click Model Card -> Click "Edit" -> Change Something -> Click "Update" -> And then want to see different version through the Selection Button, all version tends to be the same (Seems like it has be overwritten).

![Image](https://user-images.githubusercontent.com/40858699/229932003-5a0e76a2-8160-4008-b103-5525775fa0ab.png)

5. It is better to have a model version update button here

![Image](https://user-images.githubusercontent.com/40858699/229940745-05f84bb6-30a4-4c2e-9c07-ffc26c813d9f.png)

**Comment by chaoyanghe** [comment]
solutions to issue 2&5:

1. 多版本共存模式 @ShokWang 
支持同model name但是不同model_version的创建。现状：会报错，不容许同名model_name的创建

2. 替换模式 @RyanTrojans @ShokWang 
"Edit"按钮：create -> delete。风险点：当单个node上的GPU/CPU memory cost > 50%时，可能创建不成功（OOM）；优化点：切换时间？控制在毫秒级，甚至0掉线

3. 先删除后创建模式 @Raphael-Jin

**Comment by fedml-dimitris** [comment]
This issue is not related directly to the open-source FedML library. Closing.
