### ISSUE TITLE
Command_round cannot be more than 200 ?

### ISSUE THREAD

**Issue by jerryandcse** [FedML-AI/FedML#86]
I used `FedML-Server/client_simulator/mobile_client_simulator.py` to ran two cllients ,
and used `FedML-Server/executor/app.py` to ran a server on the same PC.
Even I set the argument "comm_round" to 250, but the learning will be stuck at round 200.
But if I set the "comm_round" to 50 , the learning will be finished at round 50.
Picture:
![client](https://user-images.githubusercontent.com/11406096/102991214-c1be2c00-4553-11eb-9cf4-adb64d4c8b32.png)
(Client)
![server](https://user-images.githubusercontent.com/11406096/102991287-e61a0880-4553-11eb-91d7-b1ae01e312dd.png)
(Server)

**Comment by mzp0625** [comment]
Please run `server_start.sh` under `FedML-Server/executor` with --comm_round set as 250 first. This step calls the preprocessor to produce datasets for 250 rounds of iteration. 

[
<img width="582" alt="Screen Shot 2021-01-01 at 1 27 16 PM" src="https://user-images.githubusercontent.com/31434232/103446495-1be67d80-4c35-11eb-81cc-3a494bfde0bd.png">
](url)

**Comment by jerryandcse** [comment]
> Please run `server_start.sh` under `FedML-Server/executor` with --comm_round set as 250 first. This step calls the preprocessor to produce datasets for 250 rounds of iteration.
> 
> [ <img alt="Screen Shot 2021-01-01 at 1 27 16 PM" width="582" src="https://user-images.githubusercontent.com/31434232/103446495-1be67d80-4c35-11eb-81cc-3a494bfde0bd.png"> ](url)

It works. Thank you very much!!
