### ISSUE TITLE
Are all datasets provided in FedML non-i.i.d?

### ISSUE THREAD

**Issue by zzp1012** [FedML-AI/FedML#93]
I am doing research with FedML now and I want to confirm whether the datasets provided in FedML are non-i.i.d or not.

**Comment by chaoyanghe** [comment]
you can use both by setting the partition method. An example is here:
https://github.com/FedML-AI/FedML/blob/49a3c760c7d166d6730c118eb0aafae872c852bf/fedml_experiments/distributed/fedavg/main_fedavg.py#L61

**Comment by zzp1012** [comment]
> you can use both by setting the partition method. An example is here:
> https://github.com/FedML-AI/FedML/blob/49a3c760c7d166d6730c118eb0aafae872c852bf/fedml_experiments/distributed/fedavg/main_fedavg.py#L61

Thank you for ur reply, but I still have two questions.

1. I saw the file `main_fedavg.py` use this argument only for datasets ILSVRC2012, gld23k, gld160k, cifar10, cifar100, and cinic10, how about `MNIST`, `Federated MNIST`, and `Shakespeare`? 

2. How to set the argument to make the dataset become non-i.i.d?

Again, thank you for ur reply.

**Comment by chaoyanghe** [comment]
I remember these three are already non-IID. You can double check our code for details.
We will release more documents for clarification after ICML deadline. Thanks for your questions.

**Comment by zzp1012** [comment]
Thank u. I will close the issue.
