### ISSUE TITLE
A small typo. Please change CLINET to CLIENT.

### ISSUE THREAD

**Issue by sugaruncle** [FedML-AI/FedML#94]
A small typo. Please change CLINET to CLIENT.

![image](https://user-images.githubusercontent.com/35253472/105183224-e87a7d00-5b68-11eb-80aa-e253549e6820.png)

https://github.com/FedML-AI/FedML/blob/49a3c760c7d166d6730c118eb0aafae872c852bf/fedml_api/data_preprocessing/FederatedEMNIST/data_loader.py

**Comment by Elliebababa** [comment]
Hi, thanks for the call out! Fixed it.
